### ISSUE TITLE
Issues in Chrome

### ISSUE THREAD

**Issue by GroupHouse** [quark-dev/Phonon-Framework#1]
Could just be me, but I cannot seem to get the menu system to work reliably. It does not even work for me on the demo site. It works fine for IE and firefox, but not in Chrome which makes working with Ripple and Cordova pretty hard. 

http://phonon.quarkdev.com/components

**Comment by BafS** [comment]
Tanks for the feedback. For me it works with chrome. Witch version of chrome do you use ?

**Comment by GroupHouse** [comment]
Newest version Version 41.0.2272.89 - works on other peoples machines just not mine :(

**Comment by Qathom** [comment]
Me too, it is working on Chrome. What does not work exactly?
Are you talking about the physical menu-button on Android devices ?
If it is the case, you are right, it is not yet supported!

A workaround:

    // Toggle the menu
    function toggleMenu () {
        Phonon.Menu('#my-menu').toggle();
    }

    document.addEventListener('menubutton', toggleMenu, false);
