### ISSUE TITLE
CrossDomain flag is not handled correctly

### ISSUE THREAD

**Issue by HugoCrd** [quark-dev/Phonon-Framework#10]
Hi !

This line seems to be wrong : 
https://github.com/quark-dev/Phonon-Framework/blob/244fa27828ab90aa6e54f54da765d8fe704a8c99/src/js/core/ajax.js#L66
I think it should be :
```var crossDomain = (typeof opts.crossDomain === 'boolean' ? opts.crossDomain : false);```

For now, CORS is activated when ```opts.crossDomain``` equals ```"boolean"``` which is odd ;)

Having fun with Phonon so far, thanks!

**Comment by Qathom** [comment]
Hi,

You are right! Thank you for your remark.
Happy to learn that you have fun with Phonon :)
