### ISSUE TITLE
Checkbox and radio not working in current trunk

### ISSUE THREAD

**Issue by vinay1069** [quark-dev/Phonon-Framework#101]
Hello,

Looks like checkbox and radio box are broken in current trunk, Tried it with kitchen sink. 

![capture](https://cloud.githubusercontent.com/assets/1731643/13576211/8cacdb94-e4b2-11e5-9ec6-360c7ca82cf8.PNG)

Any ideas? 

Thanks!

**Comment by vinay1069** [comment]
seems to be working with 1.1.9 release. After that is is broken

**Comment by Qathom** [comment]
Hello @vinay1069 ,

Thank you for reporting this.
mikesten has made a pull request, it is now working again.
I create the release 1.2.2 asap.

**Comment by vinay1069** [comment]
Thanks for fix.. Cheers!
