### ISSUE TITLE
Buttons on dialog not visible

### ISSUE THREAD

**Issue by vinay1069** [quark-dev/Phonon-Framework#104]
Seems like buttons on dialog are no longer visible. tested it on trunk. 
![capture](https://cloud.githubusercontent.com/assets/1731643/13670026/650c2b5c-e6ed-11e5-9dc9-d068c0ac8f8d.PNG)

Fix will be appreciated. Thanks!

**Comment by John-Henrique** [comment]
:+1: 
Really exists a mistake of the last release

**Comment by Qathom** [comment]
Hi @vinay1069,

Thank you for reporting this.
I confirm. This has been corrected in the latest release (v.1.2.3).

Please, reopen the issue if it has not been fixed for you.

**Comment by vinay1069** [comment]
Thanks Guys :+1:
