### ISSUE TITLE
Riot self.update() not working

### ISSUE THREAD

**Issue by vinay1069** [quark-dev/Phonon-Framework#106]
Hello,

Not sure if this qualify as bug but somehow `self.update()` is not working after 1st load. Please see attached sample project which have that bug
[riot-sample.zip](https://github.com/quark-dev/Phonon-Framework/files/183938/riot-sample.zip)

steps
1. run index.html from brackets
2. Orders page will open
3. open side panel and go to profile page
4. text box with value 'vinay' will load
5. Edit text box value to say 'Test'
6. navigate back to Orders
7. and again open Profile page

In profile page 'vinay' value should again get reloaded 

```
this.on('ready', function () {
            self.user = 'vinay'
            self.update();
        })
```

but somehow `self.update()` is not working. and value in text box remain test.

Hope this make sense.. Will really appreciate your input.

**Comment by Qathom** [comment]
Hi @vinay1069,

Is the callback "ready" called as expected?

**Comment by vinay1069** [comment]
@Qathom Yes actually, it executes self.update() everytime.

**Comment by Ajusa** [comment]
Hi @vinay1069 
I think the issue you have is right here:
```
<input type="text" id="profile_user_name" placeholder="Full Name" value="{user}">
```
instead of value="{user}", I think it should be value={user}
This is just a guess, I was unable to get your code to render.
Good luck!
