### ISSUE TITLE
JS tags in templates referenced by app.js

### ISSUE THREAD

**Issue by Nattefrost** [quark-dev/Phonon-Framework#108]
Hi, it's not an issue per-say (could be, I actually don't know) but more of a question. I saw that any JS contained in the script tags doesn't work if it is in a template that is referenced in app.js via `app.on({page: 'pagename', content: pagetemplate.html},.` The tags and what's within seems to be interpreted as text, it is in the page -when inspecting it- but not recognized as executable javascript.

So the question is : is it deliberate from phonon dev part? If not, is it in your plans? Maybe I'm just doing something wrong.
After fiddling with it for a bit I figured I could make it work by doing this : 
line 1424 in phonon.js : 
```js
    if(opts.useI18n) {
            phonon.i18n().bind(virtualElPage, function() {
                elPage.innerHTML = virtualElPage.innerHTML;
                try {
                    var s = virtualElPage.getElementsByTagName("script");
                    for(var i=0; i< s.length; i++) {
                        $.globalEval(s[i].innerHTML);
                    }   
                } catch(e) {
                    console.log(e);
                }
                  fn();
                });
              } else {
                  elPage.innerHTML = virtualElPage.innerHTML;
                  try {
                      var s = virtualElPage.getElementsByTagName("script");
                      for(var i =0;i< s.length; i++) {
                          $.globalEval(s[i].innerHTML);
                  }   
                } catch(e) {
                    console.log(e);
                }
                fn();
          }
```

**Comment by Qathom** [comment]
Hi @Nattefrost,

Nice idea! :)
I just added this feature, but without the need of jQuery.
I'll create the release asap.
