### ISSUE TITLE
changePage does not do anything when an indicator is shown

### ISSUE THREAD

**Issue by HugoCrd** [quark-dev/Phonon-Framework#11]
What I want to do : 
I got to go to another page after an Ajax request.
I want to show an Indicator while request is being done (it's a login request).

What it does : 
```changePage``` does not do anything if indicator is present in the page. Even if I close it before calling 

```javascript
            var dialog = phonon.indicator("Login...");

            phonon.ajax({
                method: 'POST',
                url: apiUrl+'/myuri',
                crossDomain: true,
                dataType: 'json',
                data: {some: things},
                success: function(res) {
                    dialog.close();
                    phonon.navigator().changePage('secondpage');
                },
                error: function(err, req) {
                    dialog.close();
                }
            });
```

This works as soon as I remove this indicator.

Any idea?

**Comment by Qathom** [comment]
Someone also had this issue (#9). I will modify this asap! For the moment, here is a solution:

The navigator module checks if a dialog is visible. If it is the case, it will cancel the page and close the active dialog instead (native-like purpose). Try to put a timeout before changing the page like so:
```javascript
window.setTimeout(function() {
    app.changePage('secondpage');
}, 500); /* 500ms should be enough (time to dismiss the dialog) */
```
It should fix your problem. Please let me know.

**Comment by HugoCrd** [comment]
It does the trick for now, but a clean solution would be a __lot__ better ;)

**Comment by HugoCrd** [comment]
Closing this as I just realized it's a duplicate of #9...
