### ISSUE TITLE
Feature Over scroll effect

### ISSUE THREAD

**Issue by anggaranc** [quark-dev/Phonon-Framework#112]
what phonon have a scroll over effect like this? 
[picture](http://i.stack.imgur.com/MGxck.jpg)

**Comment by gRegorLove** [comment]
If you're using Cordova, I think you want to add these to your config.xml:

`<preference name="DisallowOverscroll" value="true" />`
`<preference name="webviewbounce" value="false" />`

via https://chrisgriffith.wordpress.com/2014/10/10/phonegap-development-mistakes-and-how-to-avoid-them/
