### ISSUE TITLE
How to get selected value of popover

### ISSUE THREAD

**Issue by sunilmca88** [quark-dev/Phonon-Framework#113]
I'm using phonon with Cordova and using popover as a dropdown selector but unable to get the selected value of the popover. Please let me know the best way possible for this

**Comment by Ajusa** [comment]
I think that a drop down component should be made. The popover and the dropdown are two different things. @Qathom would have to make it, since I didn't see it in the docs.

**Comment by Qathom** [comment]
Hi @sunilmca88 and @Ajusa,

The latest version 1.3.0 offer you more possibilities.
```js
var popover = phonon.popover()
    .setList(['a', 'b', 'c'])
    .attachButton('.my-button', true)
    .onItemChanged(function (data) {
        console.log(data);
    }).openFrom('.my-button')
```

More information can be found [in the docs](http://phonon.quarkdev.com/docs/popovers).
