### ISSUE TITLE
Accordion not work and freeze header-bar in Panel Component

### ISSUE THREAD

**Issue by John-Henrique** [quark-dev/Phonon-Framework#114]
Accordion simple freeze when is in a panel.
Tested in:
Google Chrome (works fine)
Android 4.1.2 (don't works)
````html

<div id="myPanelexample" class="panel-full">
        <header class="header-bar">
            <a class="btn icon icon-close pull-right" href="#" data-panel-close="true"></a>
            <h1 class="title">Nova conta</h1>
        </header>

        <div class="content">
            <div class="padded-full">
				<ul class="list">
					<li>
						<i class="pull-right icon icon-expand-more"></i>
						<a href="#link1" class="padded-list">Link 1</a>
						<div class="accordion-content">
						  Element 1
						</div>
					</li>
				</ul>

				<input type="text" placeholder="nome conta" class="nome">
				<button class="btn fit-parent primary padded-top salvar">Salvar</button>
				
			</div>
        </div>
</div>
````
![screenshot_2016-04-01-11-33-23](https://cloud.githubusercontent.com/assets/332925/14210145/16341d10-f7fe-11e5-99c6-38faa6884d5a.png)

![screenshot_2016-04-01-11-33-38](https://cloud.githubusercontent.com/assets/332925/14210151/1f4f4a78-f7fe-11e5-9f9d-14d75e2f0790.png)

![screenshot_2016-04-01-11-33-10](https://cloud.githubusercontent.com/assets/332925/14210161/24bdeb4a-f7fe-11e5-83e4-0c536b33bbcc.png)

**Comment by Qathom** [comment]
Hi @John-Henrique,

Thank you for reporting this.
Accordion lists are now supported in panels and side panels.
I will create a release asap! :)

**Comment by John-Henrique** [comment]
Thank you
