### ISSUE TITLE
Page templates not working

### ISSUE THREAD

**Issue by sklas** [quark-dev/Phonon-Framework#115]
Hi,

I tried to start an app with Phonon and everything works fine if I define all html in index.html, but when I try to include pages as page templates they just don't load.

I used cordova browser with firefox and chromium.

The pizza-app example is also not working.

**Comment by John-Henrique** [comment]
Young need use a webserver. Can you see the console, have any error there?
Em 03/04/2016 06:48, "sklas" <notifications@github.com> escreveu:

**Comment by Qathom** [comment]
Hi @sklas,

Thank you for reporting.
Is your code working without Cordova?
I also need your Cordova version to debug. :)

Thanks.
