### ISSUE TITLE
data-param not working

### ISSUE THREAD

**Issue by rmdydo** [quark-dev/Phonon-Framework#116]
I am trying to add a parameter to a button with navigation as shown in the documentation:
<button class="btn" data-navigation="page-name" data-param="my-value">Go to page</button>

After the page transition, the param is not in the url or passed in the onhashchange event. I looked at the source code and could not find any code related to "data-param". Was this removed or is the documentation no longer correct?

**Comment by Qathom** [comment]
Hi,

Thank you for opening this issue!
You are right, the data-param attribute is depreciated (and I forgot to remove in the docs). Sorry.
You can add paramters with **data-navigation** directly like the following code example:
```html
<button class="btn" data-navigation="page-name/a/b/c">Go to page</button>
```

The documentation has been updated: [http://phonon.quarkdev.com/docs/navigator](http://phonon.quarkdev.com/docs/navigator)
