### ISSUE TITLE
Dialog 'confirm' callback is called multiple times if dialog was previously canceled

### ISSUE THREAD

**Issue by michaelkoetter** [quark-dev/Phonon-Framework#117]
I'm opening a custom dialog multiple times like this

```
  let dialog = phonon.dialog(dialogEl)
  dialog.on('confirm', confirmFn)
  dialog.on('cancel', cancelFn)

  dialog.open()
```

When the dialog is opened, canceled, then opened again and confirmed, the 'confirm' callback is called twice.
In fact, the 'confirm' callback is called as many times as the dialog was previously canceled + 1 :smile:

**Comment by michaelkoetter** [comment]
In addition to the fixes in the pull request, I also had to reorder my code like this:

```
  let dialog = phonon.dialog(dialogEl)
  dialog.open()
  dialog.on('confirm', confirmFn)
  dialog.on('cancel', cancelFn)
```

ie. call open() first, then install the callbacks. Otherwise backdrop clicks would not call the cancel callback.

**Comment by Qathom** [comment]
Hi @michaelkoetter,

Thank you for reporting.
I can't reproduce this issue.. it is working on Chrome.
This is what I did in ES5:

``` javascript
function setDialog() {
	var dialog = phonon.dialog('#simple-dialog')
    dialog.on('confirm', function () {
		console.log('CONFIRM')
	})
    dialog.on('cancel', function () {
		console.log('CANCEL')
	})

    dialog.open()
}

setDialog()

// click on a button before the timeout
setTimeout(function () {
	setDialog()
}, 3000)
```

When I click on "confirm", then reopen the dialog and click on "confirm" again, the callback is called once.

**Comment by michaelkoetter** [comment]
Yes, clicking on "Confirm" removes the callback. Try clicking on cancel a couple of times, and then "Confirm".

It is also evident from the code, the "fireEvent" function contains this

```
this.off('tap', fireEvent);
```

which only removes the event handler from the button that was clicked. So if you clicked "cancel", the 'cancel' event handler is removed - the 'confirm' handler remains installed on the button.
Then, if the dialog is created again, a second 'confirm' handler is added, etc.
When 'confirm' is finally clicked, all those event handlers are called.

**Comment by michaelkoetter** [comment]
Hi @Qathom, don't want to nag you but it's been a while - did you have a chance to test my scenario, as described above? :smiley:

**Comment by Qathom** [comment]
Hi @michaelkoetter,

I just understood the problem! I clicked on "confirm", then "cancel". Yes, the "cancel" handler is called twice.
I added the `off` function in order to remove listeners when the dialog is closed (reset the dialog).
Thank you for your help :)

I will add this fix in the next release asap!
