### ISSUE TITLE
Inputs can't be filled from Safari on iOS

### ISSUE THREAD

**Issue by HugoCrd** [quark-dev/Phonon-Framework#12]
Using iOS 8 & iOS 9, inputs in http://phonon.quarkdev.com/docs/forms can't be filled.
The animation (on first name) does work correctly, I got focus on input : cursor appears in input and keyboard shows. But typing something does not do anything.

**Comment by BafS** [comment]
The issue should be fixed (tested on Safari on ios 7 and OsX El Capitan). Reopen if you find an other bug.
Thanks for the feedback !
