### ISSUE TITLE
close icon on side-panel is not closing panel when opening via swipe gesture

### ISSUE THREAD

**Issue by oksiquatzel** [quark-dev/Phonon-Framework#120]
Hi,

when i open a side-panel with swipe gesture or mouse down/move event, the click on the close-icon does not close the side-panel. 

the error is because the variable sidePanelActive will not be set in phonon.js side-panel part. my solution is to change this code in document.on event 

        if(sidebarClose === 'true') {
            if(sidePanelActive) close(sidePanelActive);
            return;
        }

to this code

        if(sidebarClose === 'true') {
            if(sidePanelActive) {
                close(sidePanelActive);
            } else if(sidebarId !== null) {
                var sb = findSidebar(sidebarId);
                if(sb) {
                    close(sb);
                }
            }
            return;
        }

and add the attribute data-side-panel-id to the close button

`<button class="btn pull-right icon icon-close show-for-phone-only" data-side-panel-close="true" data-side-panel-id="side-panel-example"></button>`

tested on browser and android 5

Best Regards

Oksi

**Comment by Qathom** [comment]
Thank you for your contribution! :)
