### ISSUE TITLE
.on('tap', ...) does not work on Windows Desktop Chrome

### ISSUE THREAD

**Issue by flyinggorilla** [quark-dev/Phonon-Framework#121]
Hi Phonon team,

all on('tap', ...) clicks using the mouse dont work on Windows Chrome (v49). On Windows Edge browser it works fine. I am using Phonon 1.24. 

example button....
`<button id="submitwifisettings" class="btn fit-parent primary">Apply WIFI setting</button>`       

and event....
`activity.onCreate(function() {
    document.querySelector('#submitwifisettings').on('tap', onWifiSettingsSubmit);
})`

works on my iPhone (touch) and Windows Edge (touch AND mouse-click). On Windows Chrome only the "touch" on my Surface Pro 4 tablet works. 

Would be great if you could fix the mouse-click event on chrome to work with on('tap', ...

Thx!

**Comment by Qathom** [comment]
Hi @flyinggorilla,

Thank you for reporting this. Can you give me the output of the following code:

Sorry for the late reply. Can you give me the output of the following:

``` javascript
console.log('PHONON EVENTS')
console.log(phonon.event.start)
console.log(phonon.event.move)
console.log(phonon.event.end)
```

**Comment by flyinggorilla** [comment]
__Chrome output:__ (v50, Win10, 64bit)
PHONON EVENTS
touchstart
touchmove
touchend
home is opened

__Edge output:__ (v25.10586, Win10 64bit)
PHONON EVENTS
pointerdown
pointermove
pointerup
home is opened

**Comment by Qathom** [comment]
Hi @flyinggorilla,

This bug should be fixed since **[v1.4.2](https://github.com/quark-dev/Phonon-Framework/releases/tag/v1.4.2)**.

**Comment by Qathom** [comment]
Hi @flyinggorilla,

Please reopen this issue if this is not fixed yet.

**Comment by flyinggorilla** [comment]
thank you, tested now with phonon 1.4.5. works like a charm now. thanks!
