### ISSUE TITLE
i18n html option

### ISSUE THREAD

**Issue by oksiquatzel** [quark-dev/Phonon-Framework#123]
Hello,

i have added a html option to the i18n function,
because i got html entities in the json translation files and 
they are shown as Plain Text and not interpreted as html.

here the code i added to the phonon.js i18n part.

    var setHtml = function (el, text){
        el.innerHTML = text;
    }

and add to function computeNodes

    if (key === 'text') {
        setText(el, json[value]);
    } else if (key === 'html') {
        setHtml(el, json[value]);
    } 

this html related part.

In the data-i18n attributes i can now use 
html: keyname
for html 

Best Regards

Oksi

**Comment by Qathom** [comment]
Hi @oksiquatzel,

Thank you for suggesting this.
May I ask you to create a pull request for this?

Thank you for your contribution!
