### ISSUE TITLE
Side Panels + Accordion Lists

### ISSUE THREAD

**Issue by alebupal** [quark-dev/Phonon-Framework#125]
When I join   Side Panels and Accordion Lists it does not work

[http://prntscr.com/axdhrv](http://prntscr.com/axdhrv)
[http://prntscr.com/axdhz0](http://prntscr.com/axdhz0)

**Comment by Qathom** [comment]
Hi @alebupal,

Thank you for reporting this.
I just fixed this. I will create a release asap.

**Comment by osourcesol** [comment]
Hello,
I have the latest release of the framework but still I am facing the same issue, please let me know how to resolve it.

**Comment by phrdev** [comment]
How to call accordion via JS after page loaded?
