### ISSUE TITLE
Component tab isn't displaying content

### ISSUE THREAD

**Issue by John-Henrique** [quark-dev/Phonon-Framework#128]
Something strange happening with me, when using component tab sometimes the content of SECOND tab isn't displayed. See this screen shots
![1](https://cloud.githubusercontent.com/assets/332925/15095017/31e2d010-148c-11e6-8ef7-71a4da057de4.png)
![2](https://cloud.githubusercontent.com/assets/332925/15095018/31e43f9a-148c-11e6-8a71-cf57d086159a.png)
![3](https://cloud.githubusercontent.com/assets/332925/15095019/31ec9fe6-148c-11e6-9de6-b5e4d3e93326.png)
![4](https://cloud.githubusercontent.com/assets/332925/15095020/31f19686-148c-11e6-911f-390ef4041f27.png)
Before show side panel, the second tab stay empty

**Comment by Qathom** [comment]
Hi @John-Henrique,

Thank you for reporting this.
Do you still have this issue?
Which device are you testing with?

Thanks in advance.

**Comment by John-Henrique** [comment]
Hi @Qathom, actualy this problem looks like fixed. Thanks.

Testing on V1.2.9

**Comment by Qathom** [comment]
Hi @John-Henrique,

It is very strange, but it is great if it has been fixed with some (other) minor fixes.
Like always, thanks for testing on multiple devices! :)
