### ISSUE TITLE
Side Panels Docs

### ISSUE THREAD

**Issue by John-Henrique** [quark-dev/Phonon-Framework#129]
I don't know why but isn't visible programatically actions
```` javascript
phonon.panel('#my-panel-id').open();
phonon.panel('#my-panel-id').close();
````

[Side Panel Docs](http://phonon.quarkdev.com/docs/side-panels)

**Comment by Qathom** [comment]
It has been added in v1.3.0!
[Docs](http://phonon.quarkdev.com/docs/side-panels).
```js
phonon.sidePanel('#side-panel-id').open()
phonon.sidePanel('#side-panel-id').close()
```

**Comment by John-Henrique** [comment]
Nice! :+1:
