### ISSUE TITLE
Side panels close on tap?

### ISSUE THREAD

**Issue by John-Henrique** [quark-dev/Phonon-Framework#130]
I using Phonon 1.2.6 and Side panels are closed when tap in any part of panel, including links but not change pages.

**Comment by PaulRieger** [comment]
+1
works for 1.2.5
breaks on 1.2.6

**Comment by blzbruno** [comment]
+1 I
I'm using on Phonegap, I m having the same problem.

**Comment by John-Henrique** [comment]
Fixed in 1.2.9
