### ISSUE TITLE
Accordion in Panel side don't work

### ISSUE THREAD

**Issue by engkaveh** [quark-dev/Phonon-Framework#132]
Accordion in Panel side don't work
see code:
## index.html

> ```
>   ...
>     
>     <div class="side-panel side-panel-right" data-expose-aside="right" data-disable="left" data-page="pagetest" id="side-panel-new">
>         <header class="header-bar">
>             <button class="btn pull-right icon icon-close show-for-phone-only" data-side-panel-close="true"></button>
>           <div class="pull-left">
>                 <h1 class="title">test</h1>
>             </div>
>         </header>
>         <div class="content">
>           <ul class="list">
>               <li>
>                   <i class="pull-right icon icon-expand-more"></i>
>                   <a href="#link1" class="padded-list">Link 1</a>
>                   <div class="accordion-content">
>                     Element 1
>                   </div>
>               </li>
>               <li>
>                   <i class="pull-right icon icon-expand-more"></i>
>                   <a href="#link2" class="padded-list">Link 2</a>
>                   <div class="accordion-content">
>                     Element 2
>                   </div>
>               </li>
>               <li>
>                   <i class="pull-right icon icon-expand-more"></i>
>                   <a href="#link3" class="padded-list">Link 3</a>
>                   <div class="accordion-content">
>                     Element 3
>                   </div>
>               </li>
>           </ul>           
>         </div>
>     </div>
>   ...
> ```
## pagetest.html

> ```
>   <pagetest class="app-page">
>       <header class="header-bar">
>           <button class="btn icon icon-menu pull-right show-for-phone-only" data-side-panel-id="side-panel-new"></button>
>           <div class="pull-left">
>               <h1 class="title">Panel</h1>
>           </div>
>       </header>
> 
>       <div class="content">
>           <ul class="list">
>               <li>
>                   <i class="pull-right icon icon-expand-more"></i>
>                   <a href="#link1" class="padded-list">Link 1</a>
>                   <div class="accordion-content">
>                     Element 1
>                   </div>
>               </li>
>               <li>
>                   <i class="pull-right icon icon-expand-more"></i>
>                   <a href="#link2" class="padded-list">Link 2</a>
>                   <div class="accordion-content">
>                     Element 2
>                   </div>
>               </li>
>               <li>
>                   <i class="pull-right icon icon-expand-more"></i>
>                   <a href="#link3" class="padded-list">Link 3</a>
>                   <div class="accordion-content">
>                     Element 3
>                   </div>
>               </li>
>           </ul>
>       </div>
>   </pagetest>
> ```

**Comment by Qathom** [comment]
Hi @engkaveh,

Thank you for reporting this.
Does the latest release fix your issue?

**Comment by Qathom** [comment]
Closed due to inactive issue.
