### ISSUE TITLE
Side Panels Not Working on multiple pages

### ISSUE THREAD

**Issue by adrianvu** [quark-dev/Phonon-Framework#133]
Doc: http://phonon.quarkdev.com/docs/side-panels

I tried implementing the multiple pages that can enable the side panel and the side panel shows as a white blank instead of the panel. On the second page that has the button to activate the side panel is not working. Please help.

Thank you.

**Comment by adrianvu** [comment]
Updates: I tested with the new phonon.js and the problem now is that both pages show the side panels but the side-panels open and close when I click on the open sidebar button.

**Comment by Qathom** [comment]
Hi @adrianvu,

I am not sure to understand your issue.
To enable your side panel on some pages, use the attribute `data-page="home, pagetwo, ..."`.

**Comment by Qathom** [comment]
It should be fixed in 1.3.0.
Please reopen the issue if it is not the case.
