### ISSUE TITLE
Navigation is not working when currentPage hash contains name of next page.

### ISSUE THREAD

**Issue by ecorona** [quark-dev/Phonon-Framework#135]
I have the following pages structure (names):
home
payments
  ..payments_cc
  ..payments_paypal
help

if I go to page payments_cc and try to go to payments again it doesn't work because of this line of code:

```
function changePage(pageName, pageParams) {
...
var parsed = window.location.hash.split('/');
if(parsed[0].indexOf(pageObject.name) === -1 && opts.useHash) {
    window.location.hash = hash;
}
```

In my particular case the page name I want to change is contained in the current page hash so this condition is never met so it won't change the page.

You should appoint to this in your docs so other people can avoid using page names like I did.

Solved changing page names to **payment_cc** and **payment_paypal**.

**Comment by Qathom** [comment]
Hi @ecorona,

Sorry for the very late reply.

> Solved changing page names to payment_cc and payment_paypal.

Exactly. You must make your pages unique.
Please, reopen this issue if you have a suggestion.

**Comment by graham-h** [comment]
Sorry, am I missing something... not only must the page names be unique, but one page name must not be a substring of another?  I'm hitting this with a convention of naming pages like "page-items" (for a list of 'items') and "page-item" (to view/edit an instance), which doesn't feel like I'm doing a bizarre thing.  What's the rationale for this restriction?

Cheers,
Graham.
