### ISSUE TITLE
Popovers Docs small typo

### ISSUE THREAD

**Issue by TCattd** [quark-dev/Phonon-Framework#136]
Here http://phonon.quarkdev.com/docs/popovers

At the end you have this:

`
phono.popover('#my-popover').open();
phono.popover('#my-popover').close();
`

It should be:
`
phonon.popover('#my-popover').open();
phonon.popover('#my-popover').close();
`

Don't know if anyone can contribute to the docs (can't find a repo for it), that's why i opened this issue here.

Just that.

Thanks for the good work on this framework (donated some days ago; saved many hours thanks to you guys).

**Comment by Qathom** [comment]
Hi @TCattd,

Thank you for reporting this!
I just corrected this on the docs: [http://phonon.quarkdev.com/docs/popovers](http://phonon.quarkdev.com/docs/popovers).
For the moment, it is not possible to edit the docs.

Yes, thank you very much for your support! It gives motivation :)
