### ISSUE TITLE
Issue with OS nVer using Phonon.js in emulator (i.e. Intel XDK - Chromium)

### ISSUE THREAD

**Issue by jlhart** [quark-dev/Phonon-Framework#137]
First want to say...Love the framework!

I am using Intel's XDK Mobile development platform and I am working on a mobile app project using the phonon.js framework.  I am running into an issue with the emulator's emulated OS Version being interpreted incorrectly inside of phonon.js.  ~line 119 inside of phonon.js I had to modify it to the following to make it load in the emulator and still allow it to load correctly on the phone:

```
       case 'iOS':
            osVersion = /OS (\d+)_(\d+)_?(\d+)?/.exec(nVer);
            //ADDED TO ALLOW XDK EMULATION OF i DEVICES
            if(osVersion===null){
                osVersion = '8_0_0'; // default to 8.0.0
                osVersion = osVersion[0] + '.' + osVersion[2] + '.' + (osVersion[3] | 0);
            } else {
                osVersion = osVersion[1] + '.' + osVersion[2] + '.' + (osVersion[3] | 0);
            }
            //END OF ADDED EMULATOR DEFAULTS
            break;
```

Can this be included or some other solution provided to allow for correct interpretation of emulator OS versions? (refer to Intel Forum post: [Click Here](https://software.intel.com/en-us/forums/intel-xdk/topic/629371) for more detailed information)

**Comment by Qathom** [comment]
Hi @jlhart,

Thank you for reporting this.
I fixed this, it will be available in version **1.2.7** coming asap.
