### ISSUE TITLE
Using with Vue.js

### ISSUE THREAD

**Issue by musicformellons** [quark-dev/Phonon-Framework#139]
I am trying to use the pizza-with-vue example and integrate phonon with vue. I get:
ERROR in ./src/components/App.vue

  ✘  http://eslint.org/docs/rules/no-undef  'phonon' is not defined  
  /home/usr/pq02/src/components/App.vue:30:14
        app: phonon.navigator()
                ^

  ✘  http://eslint.org/docs/rules/no-undef  'phonon' is not defined  
  /home/usr/pq02/src/components/App.vue:34:7
      phonon.options({
         ^

✘ 2 problems (2 errors, 0 warnings)

Errors:
  2  http://eslint.org/docs/rules/no-undef

ERROR in ./src/components/PageTwo.vue

  ✘  http://eslint.org/docs/rules/no-undef  'phonon' is not defined  
  /home/usr/pq02/src/components/PageTwo.vue:62:11
          phonon.alert('Before leaving this page, you must perform an action.', 'Action required')
             ^

  ✘  http://eslint.org/docs/rules/no-undef  'phonon' is not defined  
  /home/usr/pq02/src/components/PageTwo.vue:77:11
          phonon.alert('Thank you for your order!', 'Dear customer')
             ^

  ✘  http://eslint.org/docs/rules/no-undef  'phonon' is not defined  
  /home/usr/pq02/src/components/PageTwo.vue:79:11
          phonon.alert('Your order has been canceled.', 'Dear customer')
             ^

✘ 3 problems (3 errors, 0 warnings)

**Comment by Qathom** [comment]
Hi @musicformellons,

Thank you for reporting this.
It has been fixed in release **1.2.7**!
