### ISSUE TITLE
pizza-app not working in Chrome Version 51.0.2704.106 (64-bit)

### ISSUE THREAD

**Issue by musicformellons** [quark-dev/Phonon-Framework#140]
The pizza-app example does not work in my Chrome. It works in Firefox.

See console messages:
![screenshot from 2016-06-24 14-09-41](https://cloud.githubusercontent.com/assets/10334123/16337450/e1222040-3a15-11e6-9e54-394bc97e14a5.png)

**Comment by Qathom** [comment]
Hi @musicformellons,

Are you running your project with a server?

**Comment by Ajusa** [comment]
npm install live-server
live-server
Run those commands in the directory of the example app

I would close this issue if I were you @Qathom
