### ISSUE TITLE
Tab indicator has the wrong location

### ISSUE THREAD

**Issue by Lukas0025** [quark-dev/Phonon-Framework#142]
Tab indicator has the wrong location. Even here also : http://phonon.quarkdev.com/App/public/phonon/kitchen-sink/#!pagetabs
![image](https://cloud.githubusercontent.com/assets/10090137/16715991/c87bb434-46ef-11e6-8fe1-7c9a145c655d.png)

**Comment by Lukas0025** [comment]
I found the location tab Indicator is right wrong is positioned Obekt over him , but only if all three Obekt have only length but if they are the same length , everything works correctly.
![image](https://cloud.githubusercontent.com/assets/10090137/16716117/8ac706ee-46f3-11e6-8d41-acebe6811adb.png)

**Comment by Qathom** [comment]
Hi @Lukas0025 ,

Thank you for opening an issue.
I tried to fix this. It will be available for the version **1.2.7** coming asap.

**Comment by John-Henrique** [comment]
Not fixed

Tested on 
Phonon (min) V1.2.9
Android 4
Android 5.1
Google Chrome
Mozila Firefox

**Comment by Qathom** [comment]
Hi @John-Henrique and @Lukas0025,

I think that I found the bug héhé.
Can you please try the latest css file [phonon.css](https://github.com/quark-dev/Phonon-Framework/blob/master/dist/css/phonon.min.css).

Thank you in advance!

**Comment by John-Henrique** [comment]
Fixed in V 1.3.0

**Comment by Qathom** [comment]
Thank you @John-Henrique!
I close the issue.
