### ISSUE TITLE
i18n on xhr problem

### ISSUE THREAD

**Issue by ddonny** [quark-dev/Phonon-Framework#143]
hi, i'm trying the i18n example, but not working. looks like there is no file json found. but actually it is already well placed.

![xhrproblem](https://cloud.githubusercontent.com/assets/6001181/16755313/74bcc1ee-4825-11e6-95d1-421996335f78.PNG)

maybe there some guidance to make it working?
using phonon core version 1.2.1

**Comment by Qathom** [comment]
Hi,

Did you already fix your issue?
Are you sure you can make a GET request correctly (by using your browser for example)?
You can debug easier with the **Network** tab.

**Comment by ddonny** [comment]
Hi Qathom, thank you for your reply,
i guess there is problem with onreadystatechange after request language file.

i change the phonon-core.js

```
var xhr = new XMLHttpRequest();

        xhr.open('GET', opts.directory + locale + '.json', true);
        if(xhr.overrideMimeType) xhr.overrideMimeType('application/json; charset=utf-8');

        xhr.onreadystatechange = function () {
            if (xhr.readyState === 4) {
                if (xhr.status === 200) {

                    jsonCache = JSON.parse(xhr.responseText);
                    callback(JSON.parse(xhr.responseText));

                } else {

                    if(opts.localePreferred) {

                        // The preferred locale is not available
                        opts.localePreferred = null;

                        console.log('The language [' + locale + '] is not available, loading ' + opts.localeFallback);

                        getAll(function (json) {
                            jsonCache = json;
                            callback(json);
                        });
                    } else {
                        throw new Error('The default locale ['+opts.directory+opts.localeFallback+'.json] file is not found');
                    }
                }
            }
        };
        xhr.send('');
```

into

```
var xhr = new XMLHttpRequest();
        xhr.open("GET", opts.directory + locale + '.json', true);
        xhr.onreadystatechange = function () {
            if (xhr.readyState === 4) {
                if (xhr.status === 200 || xhr.status == 0) {
                    jsonCache = JSON.parse(xhr.responseText);
                    callback(JSON.parse(xhr.responseText));
                }
            }
        };
        xhr.send(null);
```
and it's worked.

**Comment by Qathom** [comment]
Hi @ddonny,

Thank you for your reply.
The status is 0 when the file is opened in the browser via the **file protocol**.
I am not sure if it is a good idea to load data with the file protocol instead of http.
Did you try to load data without the file protocol?

**Comment by ddonny** [comment]
oh yes i see, that why i always got 0 status, by the way many people try using this framework with phonegap/cordova, Will there be any change in future for phonon-core.js ? thanks anyway qathom.
