### ISSUE TITLE
Phonon -- The Good and....the not so good

### ISSUE THREAD

**Issue by EtKit** [quark-dev/Phonon-Framework#147]
I discovered Phonon just two days ago - and loved it.  Thanks a lot for creating this, Quarkdev.  I have run into a few minor issues
- Surprise - there is no UI component to create a radio button group - a la jQuery UI/Mobile.  I fixed that with a spot of CSS.
- With that done I thought I would hook in the "tap" event for my new radio group controls. Surprise again - document.querySelector(...).on is good but document.querySelectorAll(...).on does not exist.

I have fixed that for now with a small DOM extension

`document.hookAll = function(tag,event,callback)
{
 var tags = document.querySelectorAll(tag);
 for(var i=0;i < tags.length;i++) tags[i].on(event,callback);
};
`

One of the nicest things about Phonon is that its codebase is small = manageable and hackable.  However, it would be nice to have some notes in the documentation on how to extend Phonon.

One of the other things that surprised me - the "library agnostic" bit on the home page lists jQuery but not Zepto.  A rather strange omission for a framework that is intended to target hybrid apps.

**Comment by Qathom** [comment]
Hi @EtKit,

Thank you for opening this issue.

_With that done I thought I would hook in the "tap" event for my new radio group controls. Surprise again - document.querySelector(...).on is good but document.querySelectorAll(...).on does not exist._

Nice point. I added the events `on` and `off` to the `NodeList` object which means it is now possible to add events to many selectors by using `querySelectorAll(...).on(...)`.


_Surprise - there is no UI component to create a radio button group - a la jQuery UI/Mobile. I fixed that with a spot of CSS._

Do you mean radio buttons displayed horizontally?


_One of the other things that surprised me - the "library agnostic" bit on the home page lists jQuery but not Zepto. A rather strange omission for a framework that is intended to target hybrid apps._

Yes I will add Zepto to the list! :)

**Comment by EtKit** [comment]
Hi @Qathom,

Yes, I did mean a horizontal group of radio buttons.  In general Phonon appears a bit deficient in the area of buttons - toggles, radio groups... . I have ended up spinning my own.  If the docs were a bit more clear on how to create UI components (I don't really want to digress into studying how it works) I would contribute my effort.  As things stand what I have done is only good for my own use.

**Comment by andreujuanc** [comment]
I think @Qathom is probably working alone on this. We should discuss LOTS and help him with some code, since you just said it, its small codebase and really manageble to work on.

**Comment by Qathom** [comment]
@EtKit I am very opened to suggested components, you are welcome for contributing on radio groups.
Phonon uses Stylus, if you want to add a component in forms, you can edit the following file: [forms.styl](https://github.com/quark-dev/Phonon-Framework/blob/master/src/stylus/components/forms.styl).
To compile the stylus file, you need to run the `gulp` command. Compiled files are available in the `dist` directory ([forms.css](https://github.com/quark-dev/Phonon-Framework/blob/master/dist/css/components/forms.css)).
For using gulp, please run `npm install` then `gulp`.

Let me know if something is missing or if you need something else.
