### ISSUE TITLE
Popovers on iOS 9.x can't be used

### ISSUE THREAD

**Issue by TCattd** [quark-dev/Phonon-Framework#148]
Like the title says.

Basically can't use any Popover on iOS9.
They don't work on the Kitchen Sink using Safari (tested on device), and also don't work inside a Cordova App (demo in the video, on device, after the Kitchen Sink part).

When you try to scroll through the options (up or down), the popover just disappear.

I've recorded a quick video of this issue: https://www.youtube.com/watch?v=qSjPd3xpKNI

Latest Phonon version up today.

**Comment by Qathom** [comment]
Hi @TCattd,

Thank you for opening this issue and for the video.
I think I know why this is happening.
Did you put your `.popover` inside the page scope?
Please, can you try to put the popover just after `<body>`.

Thank you in advance

**Comment by TCattd** [comment]
Yes @Qathom that make the popover work on iOS9. Tested on device, inside the cordova app.

But it's really a non desired solution. We have a lot of js templates going on inside every page that's are populated on page load with a 3rd party api, and put this popovers outside the page breaks everything and make a mess on the index (we use several of those).

There's another viable solution to this? considering that on android the same popovers works as expected inside the page scope.

Thanks for the reply @Qathom ;)

**Comment by Qathom** [comment]
I understand your problem @TCattd.
I just added an **[API for popovers](http://phonon.quarkdev.com/docs/popovers)**. Phonon can generate your popovers with the following code:

```js
var popover = phonon.popover()
    .setList(['a', 'b', 'c'])
    .onItemChanged(function (data) {
        console.log(data)
    }).open('right')
```
If phonon.popover() is empty, it will create a new instance. Then you can set a simple array of values or an array of objects.
If you need to open the popover above a button, use `.openFrom(..)` instead.

I recommend you to read the fresh updated **[docs](http://phonon.quarkdev.com/docs/popovers)** for popovers.

What do you think? Is it amazing?

**Comment by TCattd** [comment]
It works @Qathom 

For some simple lists, we can use that for sure.

But we have some particular list that need a lot more than the markup that it's output by setList:
`<li><a class="padded-list" data-value="' + value + '">' + text + '</a></li>`

We need to pass some additional params so when a tap on an element is trigger, we know what to get (the name and the id are different). We use something like this on that list:
```
<li>
  <a class="padded-list messageCategory" data-id="id" data-code="code">
    <span data-content="title"></span>
  </a>
</li>
```

But i solved it anyways just using a similar technique that the one used on the index.html for loading the different pages with phonon.

Using something like this https://github.com/LexmarkWeb/csi.js (and/or this http://stackoverflow.com/a/9470476/920648 for folks using jQuery) to load the code for the complex popovers (those that use a template engine to be populated) from the index.html file, and it now works and it's not a mess to work with :)

Thanks for the help (and the new API) @Qathom.
Have a great day!

**Comment by Qathom** [comment]
Hi @TCattd,

Thank you for your feedback.
I added a custom list item builder as the second argument for `setList`.
I push this asap ;).

```js
popover.setList(['a', 'b', 'c'], function (item) {
    var text = typeof item === 'string' ? item : item.text;
    var value = typeof item === 'string' ? item : item.value;
    return '<li><a class="padded-list" data-value="' + value + '">' + text + '</a></li>';
});
```

**Comment by TCattd** [comment]
That's nice @Qathom thanks!

As soon as i have some extra time, will migrate those lists to the new API.

Thanks so much for the work :)
