### ISSUE TITLE
Docs: floating action markup position (affects iOS9)

### ISSUE THREAD

**Issue by TCattd** [quark-dev/Phonon-Framework#152]
About this:
http://phonon.quarkdev.com/docs/floating-actions

We had our pages set up like this:

```
<page-gatekeeper class="app-page">
	<header class="header-bar">
		<div class="center">
			<button class="btn pull-left icon icon-menu" data-side-panel-id="side-home"></button>
			<div class="center">
				Page title
			</div>
		</div>
	</header>

	<div class="content">
		<div class="padded-full page-gatekeeper">

			Page content

			<div class="buttonContainer">
				<button class="hide floating-action mdi mdi-plus active btn-primary"></button>
			</div>

		</div>
	</div> <!-- / .content -->

</page-gatekeeper>
```

That works on Android, and on web. But on iOS9 the floating button is stuck on the initial loading position and, when scroll, it won't stay fixed on screen even if the button has the correct position: fixed on it.

After some head scratching, i realize that the examples at http://phonon.quarkdev.com/docs/floating-actions have the floating button outside the "content", like this:

```
<page-gatekeeper class="app-page">
	<header class="header-bar">
		<div class="center">
			<button class="btn pull-left icon icon-menu" data-side-panel-id="side-home"></button>
			<div class="center">
				Page title
			</div>
		</div>
	</header>

	<div class="content">
		<div class="padded-full page-gatekeeper">

			Page content

		</div>
	</div> <!-- / .content -->

	<div class="buttonContainer">
		<button class="hide floating-action mdi mdi-plus active btn-primary"></button>
	</div>
</page-gatekeeper>
```

I moved the markup on the app, and it's working fine now :)

The docs should specify where the button's markup should go.
If it's not a bug: as i said, on web and android, the button inside the "content" area works just fine.

Thanks for the time again ;)

**Comment by Qathom** [comment]
Hi @TCattd,

Thank you for opening this issue. :)
This has been corrected, thank you for your contribution!
