### ISSUE TITLE
i18n xhr problem loading local file

### ISSUE THREAD

**Issue by PaulRieger** [quark-dev/Phonon-Framework#156]
phonon.js line 904

` if (xhr.status === 200) {`

should be

`if (xhr.status === 200 || !xhr.status && xhr.responseText.length) {`

see https://github.com/quark-dev/Phonon-Framework/issues/41

**Comment by Qathom** [comment]
Hi @PaulRieger,

Thank you for reporting this.
I added the same patch as [#41](https://github.com/quark-dev/Phonon-Framework/issues/41).
It will be available asap as a release.
