### ISSUE TITLE
Side panels won't work on Cordova with Crosswalk enabled (latest version) on Android

### ISSUE THREAD

**Issue by TCattd** [quark-dev/Phonon-Framework#157]
Phonon's Side panels are broken using Crosswalk from version 1.5.0 to the latest one. But on old Crosswalk version 1.4.0 Side panels works.
I can reproduce this every time, and in a fresh Cordova app (just with Phonon onto it) too.

Here's a Cordova app without Crosswalk enabled: https://www.youtube.com/watch?v=iiD0u3RagUg

here's the same Cordova app with Crosswalk enabled with:
`cordova plugin add cordova-plugin-crosswalk-webview --save`

It adds the latest crosswalk version to the app:

```
    <preference name="xwalkVersion" value="20+" />
    <preference name="xwalkCommandLine" value="--disable-pull-to-refresh-effect" />
    <preference name="xwalkMode" value="embedded" />
    <preference name="xwalkMultipleApk" value="true" />
    <plugin name="cordova-plugin-crosswalk-webview" spec="~2.0.0" />
```

https://www.youtube.com/watch?v=5XwPX3z0zLI

And here it's the same app but with Crosswalk enabled with:
`cordova plugin add cordova-plugin-crosswalk-webview@1.4.0 --save`

So it adds an older version of crosswalk:

```
    <preference name="xwalkVersion" value="15+" />
    <preference name="xwalkCommandLine" value="--disable-pull-to-refresh-effect" />
    <preference name="xwalkMode" value="embedded" />
    <preference name="xwalkMultipleApk" value="true" />
    <plugin name="cordova-plugin-crosswalk-webview" spec="~1.4.0" />
```

https://www.youtube.com/watch?v=f1h8SH-3azg

It works. Always, and just with Crosswalk 1.4.0. Newer versions all break Phonon's Side panels.
Can reproduce it in a fresh app, and with Kitkat devices too.

**Comment by Qathom** [comment]
Hi @TCattd,

Thank you for opening this issue.
It is strange that it does not work with newer versions.
Do you get a JS error?

**Comment by andreujuanc** [comment]
Post sample of phonon implementation, I will try to reproduce, since in few weeks I might need to use crosswalk xP

**Comment by Qathom** [comment]
Okay, thanks for your help! :)
I'll also try to find a solution with Crosswalk.

**Comment by bdedardel** [comment]
Hi, 
I get a similar problem with my app (a text editor) with crosswalk:
- when I open a first instance of the app (from google app manager) -> side menu can be opened,
- but when I open some other instances of the app (from dropbox for example) -> side menu CANNOT be opened

As I cannot revert to crosswalk 1.4, I try without crosswalk... and everything works fine!

**Comment by evrenesat** [comment]
Hi,
In my case, at first run side-panel not works (gives an error about no side-panels found) but if I reload page from chrome remote dev tools (either by cmd+R or by calling window.location.reload()) side-panel works properly. So as a workaround I'm setting a timestamp marker, and depending to it's value, reloading the page for once and voila!

**Comment by bdedardel** [comment]
Here are the dom events during debugging:
(my current page's name is 'viewer')

### Steps when side menu is opening well 

- &lt;body class="android"> 
=> &lt;body class="android snapjs-left">

- <viewer
=> <viewer transition: all 0.3s ease;

- <viewer
=> <viewer style="transform: translate3d(288px, 0px, 0px);"

### Steps when side menu doesn't opened

- <viewer transition: all 0.3s ease; ...>

That's it !!!

**Comment by bdedardel** [comment]
The problem seems to come from *phonon.onReady* function:
- in the first instance, el.clientWidth= 288
- in the other instances, el.clientWidth= 0
and so, *settings.maxPosition* == 0 !

**Comment by bdedardel** [comment]
... and the solution (for my part) is to simply start phononjs inside the *deviceready* handler !

**Comment by Qathom** [comment]
Hi,

Yes, the good practice is to call the setup of Phonon in the `deviceready` event handler.
@TCattd : please reopen this issue if this does not fix your bug!

**Comment by TCattd** [comment]
Haven't had time to update the app that's using Phonon. When we schedule a maintenance to that app, i will test this workaround for sure.

By the way, @Qathom it would be nice to have this detail documented in Phonon's docs, so everybody will know about this quirk without have to google it and eventually hit this issue.

Phonon's docs and examples inside them are one of great things about this framework.

Anyways, thanks for the time and the help ;)
