### ISSUE TITLE
Broken .off('tap', handler)

### ISSUE THREAD

**Issue by Rcapuani** [quark-dev/Phonon-Framework#159]
Doesn't appear to remove handlers since I updated to the latest version a few days ago.

**Comment by andreujuanc** [comment]
It does work when switched as mobile device: Ctrl+Shift+M. So it might be something to do with that.

**Comment by Qathom** [comment]
HI @Rcapuani,

Thank you for reporting this issue.
The release 1.3.2 contains the patch.
