### ISSUE TITLE
params usage

### ISSUE THREAD

**Issue by metacatdud** [quark-dev/Phonon-Framework#16]
Hey man, it's me again :)

How to use req for params in the new version. I can see how to set but not how to retrieve them. 
I saw I can catch then in ``` onHashChanged``` but this method is called after ready so it's not much of a help as the page is already visible. Any advice on this one? How to properly pass params from a page to another?

Thanks!

**Comment by Qathom** [comment]
Hey!

Yes. By default, the onReady callback is called directly (1ms) when the page transition starts, but you can change this behavior with **readyDelay**!

How to use readyDelay:
```javascript
app.on({page: 'thepage', preventClose: false, content: 'thepage.html', readyDelay: 50}, function(activity) {
// activity callbacks
}
```

For example, ```javascript readyDelay: 50 ``` (time to wait until calling the ready callback = 50ms).

Typical use of OnHashChanged

Given URL: http://localhost/app/#!thepage/oneparam/second
```javascript
activity.onHashChanged(function(req) {
    req.params // will return oneparam
    req.action // will return second
});
```

**Note for hash**: if you desire to use more complicated hash routing, you can disable the default routing of Phonon and use another router with Phonon (for example AngularJS' hash routing, another vanilla router, etc.).

**Comment by metacatdud** [comment]
It's ok-ish! It's kind of tricky to relay on timeouts but until a better solution this will do. :)

Thanks!

**Comment by HugoCrd** [comment]
Wouldn't it be better be able to do : 
```
activity.onReady(function(req) {
    req.params // will return oneparam
    req.action // will return second
});
```
req containing initial params, and then use ```onHashChanged``` to track any further change?

Moreover, I don't understand why this is limited to 2 params instead of an array. Is there an underlying purpose that I am not aware of?

**Comment by Qathom** [comment]
Yes, I agree, it is better to retrieve many params (0..n).
I'll fix this asap!

**Comment by metacatdud** [comment]
+1 on @HugoCrd  suggestion!
