### ISSUE TITLE
Navigation & Side panel bug

### ISSUE THREAD

**Issue by S-anasol** [quark-dev/Phonon-Framework#162]
```
<div class="side-panel side-panel-left" data-expose-aside="left" data-disable="right" data-page="home, tags" id="side-home">
        <header class="header-bar">
            <button class="btn pull-right icon icon-close show-for-phone-only" data-side-panel-close="true"></button>
            <div class="pull-left">
                <h1 class="title">Menu</h1>
            </div>
        </header>
        <div class="content">
            <ul class="list">
                <li><a data-navigation="home" href="#!home" class="padded-list">home</a></li>
                <li><a data-navigation="tags" href="#!tags" class="padded-list">tags</a></li>
            </ul>
        </div>
    </div>

    <home data-page="true">
        .....
    </home>

    <tags data-page="true"></tags>

```

Navigation between Home and Tags makes error when it tries remove backdrop from "settings.element"

`Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.closed`

```
var closed = function() {
                            _backdrop.classList.remove('fadeout');
                            settings.element.removeChild(_backdrop); // <--  error here
                            _backdrop.off(phonon.event.transitionEnd, closed);
                        };
```

and page freezes/blinking.

Probably it want remove backdrop from home page -> but page already changed to tags. Same in other direction tags -> home.

**Comment by Qathom** [comment]
Hi @S-anasol,

Thank you for opening this issue and for your contribution.
I'll confirm your pull request. :)

**Comment by evrenesat** [comment]
Hi, 
The issue is closed but I'm getting same error with latest version. Applied the @S-anasol's  patch and it's fixed. Am I doing something wrong?

**Comment by S-anasol** [comment]
@evrenesat
maybe you use some of stable release? But fix not released yet probably or npm not updated

**Comment by evrenesat** [comment]
Yes I was using the latest stable, thank you.
