### ISSUE TITLE
phonon + vue2

### ISSUE THREAD

**Issue by bdedardel** [quark-dev/Phonon-Framework#165]
Hi,

Pizza sample is very usefull, many thanks.
Is it possible to realise a vue2 version ?
(i didn't succeed yet as I'm not a vue/vue2 specialist!) 

Regards
Benjamin

**Comment by Qathom** [comment]
HI @bdedardel,

Thank you for opening this issue.
I'll build a Vue2 version of the pizza app sample asap!

**Comment by Qathom** [comment]
Vue example has been updated to Vue2 since the v1.4.0.
