### ISSUE TITLE
phonon.min.js:2 Uncaught TypeError: Cannot read property 'style' of null(…)

### ISSUE THREAD

**Issue by John-Henrique** [quark-dev/Phonon-Framework#167]
I get this error when click in button to open side panel. In my case this error happening when using 2° option to create pages (see [Navigator](http://phonon.quarkdev.com/docs/navigator)). The side panel example works fine, but not when page is defined in external file.

Phonon 1.3.2
Android 6
Google Chrome 54.0.2840.71

**Comment by gbtux** [comment]
Hi @John-Henrique 
Can you put an example of your code ?

**Comment by Qathom** [comment]
Hi @John-Henrique,

Can you please include the non minified file (phonon.js), so that I can read the code ;).

**Comment by andreujuanc** [comment]
@John-Henrique  @Qathom phonon.js but also implementation (where you call init()) and html file where you include the tags!

Lets catch this null's exceptions!

**Comment by John-Henrique** [comment]
Using phonon.js, the error is marked in line 4439
`return typeof settings.element.style[cache.vendor+'Transform'] !== 'undefined';`

To test, this are content of:
[index.html](https://gist.github.com/John-Henrique/455b6c7b0cff711afa4130812426aff3)
[principal.html](https://gist.github.com/John-Henrique/2177f5c4949f73232feb043aa9446eab)
[app.js](https://gist.github.com/John-Henrique/10f4db2b77d33a61419b2823661f0350)

The error happening only when click in "more" button (small screens)

**Comment by andreujuanc** [comment]
John, 
 - Where is the 'more' button?
 - Would you be able to post js/contatos.js?

**Comment by John-Henrique** [comment]
I would mean button to open side panel
`<button class="btn icon icon-menu pull-left show-for-phone-only" data-side-panel-id="side-panel-example"></button>`
When I click him crash

**Comment by John-Henrique** [comment]
I tested again this time I get side panel from example path and edit, side panel works only when using 
`<home data-page="true">
	<header class="header-bar">
		<button class="btn icon icon-menu pull-left show-for-phone-only" data-side-panel-id="side-panel-example"></button>
		<div class="center">
			<h1 class="title">Side Panels</h1>
		</div>
	</header>
	<div class="content">
		
	</div> 
</home>`
this way not working (external file)
`<home data-page="true"></home>`

@Qathom any idea?

**Comment by Qathom** [comment]
Hi @John-Henrique,

Your given error `settings.element.style[cache.vendor+'Transfor` concerns Snap.JS (the library used for the swipe gesture with side panels (as @andreujuanc already said).
I can't reproduce your issue..
Can you please copy/paste your settings with `app.on(..)`?
Did you put your side panel tag in the `body` element?

**Comment by John-Henrique** [comment]
@Qathom yes, see 4 iteraction on top https://github.com/quark-dev/Phonon-Framework/issues/167#issuecomment-257192869

**Comment by Qathom** [comment]
Hi @John-Henrique,

I think that your error is here: `<div class="side-panel side-panel-left" data-expose-aside="left" data-disable="right" data-page="home" id="side-panel-example">`. More precisely with the `data-page` attribute. Your default page is principal and not home.
However, I'll add a warning message in order to avoid this issue.

**Comment by John-Henrique** [comment]
lol really, you is right
