### ISSUE TITLE
Integration with Google Maps

### ISSUE THREAD

**Issue by naurojunior** [quark-dev/Phonon-Framework#169]
Hi,
I'm trying to use google maps with Phonon, but I'm having issues and I didn't find anything in the documentation about it, maybe I'm not searching in the right way.

Google says that you have to put these lines on your code:

`map = plugin.google.maps.Map.getMap(div);
map.addEventListener(plugin.google.maps.event.MAP_READY, onMapReady);`

When I use it alone, without Phonon, the map appears correctly, but when I try to use with Phonon, the div that should contain the map don't appear.

I tried to create a new event "onDeviceReady", and tried to put inside the "app.on({page: 'home'", but none of these seems to work.

Thanks

**Comment by Qathom** [comment]
Hi @naurojunior,

Thank you for opening an issue.
Can you please paste the complete config of `app.on(...)`?
You must initialize GoogleMap **after the page is ready** (so when the page template has been added).

**Comment by naurojunior** [comment]
Thanks for your answer.

So, I started to make some tests. When I use

```
app.on({page: 'home', preventClose: false, content: null}, function(activity) {
    var map;
    var div = document.getElementById("map_canvas");
    map = plugin.google.maps.Map.getMap(div);
});
```

It won't work, but if I use
```
app.on({page: 'home', preventClose: false, content: null}, function (activity) {
  var map;
  document.addEventListener("deviceready", function() {
      var div = document.getElementById("map_canvas");
      map = plugin.google.maps.Map.getMap(div);
  }, false);
});
```

The map appears. I thought the "app.on" was executed after the "deviceReady" function... Or maybe I'm still doing something wrong

Anyway, thanks for your time

**Comment by John-Henrique** [comment]
@naurojunior try use `readyDealy:1` as param of `app.on()`

**Comment by Xeriou** [comment]
I think I have the same problem, but it's a little different that I use cordova-plugin-device not maps
So, I try some permutations 

[Google Excel for test](https://docs.google.com/spreadsheets/d/1Jx6Qj8IezxGLTWVVWbWZt45heLMnQ6jesxMSOcNqrhk/edit#gid=0)

It works all with pure text, but when I use plugin, something strange happen ... 

Anyway, 
```
document.addEventListener("deviceready", function() {
    uuid = device.uuid;
    phonon.alert(uuid);
  }, false);
```
is fine. 

But I think it is not the best solution ...

hope it will help ...

**Comment by Qathom** [comment]
Hi @naurojunior,

```js
var app = phonon.navigator()

app.on({page: 'home', ...}, function (activity) {
    // this is the main scope which permits to define the page state listeners
    activity.onCreate(function () {
        // Here you init your page
        var div = document.getElementById("map_canvas");
        map = plugin.google.maps.Map.getMap(div);
    })
})

// Make sure to start the app when Cordova is ready
document.addEventListener('deviceready', function () {
    app.start()
})
```

**Comment by Xeriou** [comment]
@Qathom  thanks !  It works !
