### ISSUE TITLE
Getting riot to work

### ISSUE THREAD

**Issue by jsantari** [quark-dev/Phonon-Framework#17]
I'm trying to use Phonon with riot as a web app. I've setup my own simple example but I get this error in chrome console when trying to load the home page.

Uncaught Error: A namespace for  home is detected, but the DOM node <home> is not found.

Update: Never mind -  got it to work after a closer look at your example.

**Comment by Qathom** [comment]
You get this error because you must declare the HTML tag for this page in your index.html file:
```javascript
<home data-page="true"></home>
```

You probably forgot to add the **data-page** atttribute.
