### ISSUE TITLE
On docs when try select code all page is selected

### ISSUE THREAD

**Issue by John-Henrique** [quark-dev/Phonon-Framework#171]
When I try select part of code of [docs page](http://phonon.quarkdev.com/docs/side-panels) all page is selected, this happening with you too?

Just only one click select all text of page 😡 
![selected page](https://cloud.githubusercontent.com/assets/332925/20462088/91909d64-aef9-11e6-83f5-e5664dada4e9.jpg)

Windows 10
Chrome 54 (64 bits)

**Comment by jack828** [comment]
Workaround for Chrome: 

Right click on page > Inspect > In Chrome's webtools select the `body` element > Under `styles` - `body` untick `user-select: all;`

**Comment by Qathom** [comment]
Hi,

Thank you very much for opening this issue.
I just fixed it!

**Comment by John-Henrique** [comment]
@jack828 thanks

@Qathom Thanks, fixed
