### ISSUE TITLE
phonon.navigator.changepage on Android 4.1.1

### ISSUE THREAD

**Issue by EtKit** [quark-dev/Phonon-Framework#175]
I am experiencing a rather strange issue on Android 4.1.1.  Here is the scenario

- The app in question starts of with its "home" screen

- In the onReady event for that screen I check to see if the user has already configured the app

- If not, I change the screen to the "config" page. 

What is happening is that the "config" page shows momentarily and the display then "slides" back to the home page.  A few debugging alerts later I find that the onReady event for the config page IS firing.  It is not clear to me what might be causing this.  Any ideas?

**Comment by John-Henrique** [comment]
Can you post your app.js from config and home? Please use block code (insert code button from comments).

**Comment by John-Henrique** [comment]
Reading again, looks like you have a validation in config sreen, so your app return back to home screen.

About onReady fire
onReady event, is fired EVERY when page is ready to user, if you want only one time, you need use onCreate, this is fired only one time.

**Comment by Qathom** [comment]
Hello @EtKit,

Did you find a solution?
You can read more about page events [in the docs](http://phonon.quarkdev.com/docs/navigator).

**Comment by Qathom** [comment]
Closed due to inactive issue.
