### ISSUE TITLE
phonon.alert text button not working in Cordova (Android)?

### ISSUE THREAD

**Issue by firstygoldfish** [quark-dev/Phonon-Framework#177]
Hi I am trying to use phonon.notif (which works it part) but the text button parameter appears to be disregarded and always states CANCEL.

phonon.notif('Project saved (' + target.getAttribute('data-order') + ')', 2000, true, 'OK');

So I expect that to put up a notification (for 2 secs) with a button link 'OK' which removes the notification early.  It still says CANCEL.  Am I using this wrong or is this an issue?

Thanks

**Comment by John-Henrique** [comment]
You is doing right. This is a bug reported in #172

**Comment by firstygoldfish** [comment]
Sorry I missed it, I did try to check first. Thanks

**Comment by John-Henrique** [comment]
No problem
