### ISSUE TITLE
Not an issue but .... Fixed footers?

### ISSUE THREAD

**Issue by firstygoldfish** [quark-dev/Phonon-Framework#178]
Hi Is there a way of creating a fixed header AND fixed footer?
Thanks

**Comment by John-Henrique** [comment]
Until this time Phonon's not have a official footer fixed (not in docs). You can do this using CSS rules...

```
footer {
	position:fixed;
	right:0px;
	bottom:0px;
	width:100%;
}
```
this case you need add tag ``footer`` in your 'screen page', the same to header... try 👍

**Comment by firstygoldfish** [comment]
That should still work. Thanks again.
