### ISSUE TITLE
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.(…)

### ISSUE THREAD

**Issue by drosanda** [quark-dev/Phonon-Framework#179]
Hi All,

I found this error, while changing page to home.

phonon.js:4417 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.(…)

At home, its going normally. But when I navigate to another page, its covered up with 
`<div` class="backdrop-panel"></div>`
Element.

**Comment by John-Henrique** [comment]
You is using the last version of Phonon? If not, see this #170

**Comment by drosanda** [comment]
Thanks  its work now
