### ISSUE TITLE
Back button in header not working

### ISSUE THREAD

**Issue by jsantari** [quark-dev/Phonon-Framework#18]
I've got a two page test setup (home and getmytopics) using riot and the back link does not work from page getmytopics. I've tried data-navigation="$previous-page" as shown below and data-navigation="home" and neither works. The <a link to home does work.Not sure what could be wrong with this.

```
<header class="header-bar">
 		<div class="left">
            <button class="btn pull-left icon icon-arrow-back" data-navigation="$previous-page">             </button>
            <h1 class="title">Back</h1>
        </div>       
        <div class="center">
            <h1 class="title">WSPR4 Your Topics</h1>
            <a href="#!home">Home</a><!-- this link works -->
        </div>
    </header>
```

**Comment by Qathom** [comment]
Is the Riot example working in your test device?
http://phonon.quarkdev.com/App/public/phonon/examples/pizza-app-with-riot/

For the page "getmytopics", did you use preventClose? 
```javascript
app.on({page: 'getmytopics', preventClose: false});
```

**Comment by jsantari** [comment]
That was it. I copied from the example and had it set to true, thanks.
