### ISSUE TITLE
Docs Floating actions component

### ISSUE THREAD

**Issue by John-Henrique** [quark-dev/Phonon-Framework#181]
Doc page have a wrong example

`<button class="floating-action icon icon-menu active btn-primary"></button>`

the correct is 
`<button class="floating-action icon icon-menu active primary"></button>`

Yes, this is a very simple error but to new users will be converted a lot issue tickets...

**Comment by Qathom** [comment]
Thank you for your remark @John-Henrique!
It has been updated.

**Comment by bdedardel** [comment]
After having upgraded to v1.3.5, right:0 and bottom:0 have been removed from css.
So, material button appears in the top/left corner instead of bottom/right by default.

You may add *style="right:0;bottom:0"* in the doc.

**Comment by John-Henrique** [comment]
@bdedardel this was changed in #183.

Now you can choose where floating action display using bottom, top... See [Floating Actions Doc](http://phonon.quarkdev.com/docs/floating-actions) 😉
