### ISSUE TITLE
Previous page sequence

### ISSUE THREAD

**Issue by Gregwar** [quark-dev/Phonon-Framework#185]
Hello,

If I have three pages A B C and I do the following pattern:

    A B [PREVIOUS] C [PREVIOUS]

Then I come back on the B page instead of the A page, how to fix that?

**Comment by John-Henrique** [comment]
You can use button linked directly to A instead of $previous-page

**Comment by Gregwar** [comment]
This was my first workaround but now my screens are more complex and there is several pathes that can lead to the same page (I did a hack to handle that manually currently)

**Comment by John-Henrique** [comment]
You have 

> PageA
> PageB
> PageC

1 - When you navigate to PageB (from PageA), return to PageA?
[  ] True    [  ] False

2 - When you navigate to PageC (from PageA), return to PageA?
[  ] True    [  ] False

3 - When you navigate to PageB (from PageC), return to PageB?
[  ] True    [  ] False

4 - What buttom you is using to back?
[  ] Phisical/Virtual backbuttom      [  ] Back button create in my app

**Comment by Gregwar** [comment]
I am talking about $previous-page here
And my expected behaviour is exactly the same as a web browser would be

**Comment by Gregwar** [comment]
And the physical button (w/ Cordova) suffers the same problem explained here

**Comment by Gregwar** [comment]
Note that this line:
https://github.com/quark-dev/Phonon-Framework/blob/master/src/js/core/navigator.js#L637

Have no effect, should it be:
    pageHistory = pageHistory.slice(inddex, 1);

?

**Comment by Gregwar** [comment]
Or, more likely

    pageHistory = pageHistory.slice(0, inddex);

**Comment by Qathom** [comment]
PR confirmed! Thank you for your contributions.
