### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by John-Henrique** [quark-dev/Phonon-Framework#189]
I regiter Phonon on [Bower](https://bower.io/), this is a package manager, helps to resolve dependences of packages, so you install your package and bower get dependences automatically.

**For what?**
Image you need install "john.js" lib, but him depend of jQuery to work, you will need install jQuery and 'john.js', but using bower you install 'john.js' and bower automatically look for dependences and in this case, install jQuery for you, every last version of lib and dependences. Understand?

To install using Bower (yes you need npm installed)
`npm install -g bower`

To install a package using Bower
`bower install <package>`
<package> can be:

- The name of package (like jquery)
- The name of project in GitHub (like quark-dev/Phonon-Framework)
- The URL of project in GitHub (like https://github.com/quark-dev/Phonon-Framework.git)
- The URL of script in any website (like http://phonon.quarkdev.com/App/public/phonon/dist/js/phonon.min.js)

To install Phonon using Bower
`bower install phonon`

**Where are the package installed?**
Bower using CLI style, so the package is installed into directory where you is. Default by SO is user directory, but you can navigate to your chosen directory.

I hope this is util for you too

**Comment by Qathom** [comment]
Hi @John-Henrique,

Thank you for adding Phonon with Bower.
I updated the [getting started](http://phonon.quarkdev.com/) guide.
Also, I added the [bower.json](https://github.com/quark-dev/Phonon-Framework/blob/master/bower.json) file.
