### ISSUE TITLE
Using params in an URL

### ISSUE THREAD

**Issue by HugoCrd** [quark-dev/Phonon-Framework#19]
Hi,

When clicking on http://phonon.quarkdev.com/App/public/phonon/examples/pizza-app-with-riot/#!pagetwo/prosciutto I'm expecting to be redirected to ```pagetwo```, with a ```prosciutto``` param. This is not the case as I'm redirected to http://phonon.quarkdev.com/App/public/phonon/examples/pizza-app-with-riot/#!home.

How to achieve such a behaviour?

**Comment by HugoCrd** [comment]
Up ;)

**Comment by Qathom** [comment]
Hi,

Sorry for the late reply! This is a good question.
The thing is that phonon.navigator().start() will init the default page which is "home" in this example.

**According to me:**
For Web Apps: it should follow your explanation.
For (Hybrid)-Cordova Apps, it should be mandatory to initialize the default page.

What do you thing?

**Comment by HugoCrd** [comment]
I think this would indeed be more web idiomatic to go to the right page in a webapp.
For hybrid apps, I can't find any use cases which would require this indeed.

**Comment by Qathom** [comment]
@HugoCrd : fixed! :)
Thank you (again) for your suggestion!

**Comment by HugoCrd** [comment]
Very nice! Thanks :)
