### ISSUE TITLE
control Accordion and a Tab bug when working with google map

### ISSUE THREAD

**Issue by ckhsu3926** [quark-dev/Phonon-Framework#190]
Hi,
This is a great framework to me :)
But Still find some question here.

I'm going to take and show a camera picture inside a Accordion List as a Form option,
but the view of picture was cut by Accordion List after taken picture by camera,
I need to hide and show this Accordion List then make view correct that means I can see the complete picture I took.
So I want know is there any method allow me control one of my Accordion List ?

And I also have a bug with Footer Tabs
The tab's nav bar and footer tabs run away when I press the backbutton.
nav bar goes left and footer tabs icon goes right and they both didn't come back !
But tab's function still working,
I can press the old side where tabs haven't gone and tab-content still change tab's content.
I try to track where is bug happen and here are what I  found :
  1.navigator will going back to previous page and return to current page .
  2.Cordova's document.on('backbutton') event work fine (even get current page) but nav bar and footer tab still run away.
So I going to searching phonon.js and toggle callClose function to fix this bug.

**Comment by John-Henrique** [comment]
Please, post print of bugs, describe him and put your code (only part interest of question), this will help us help you 😉

**Comment by ckhsu3926** [comment]
@John-Henrique thanks for your fast reply and suggest

for my first question about Accordion List's js method 
```
<ul class="list">
  <li>
    <a href="#link1" class="padded-list">附近地標<i class="pull-right icon icon-expand-more"></i></a>
    <div class="accordion-content" id="accordiontest">
      <img id="book_pic" style="width:100%">
      <button class="btn " id="book_pic_button">附近地標</button>
    </div>
  </li>
</ul>
```
http://i.imgur.com/cZ3ZBlk   this is screenshot after first show Accordion List
http://imgur.com/S1S6UkH  this is the screenshot after take picture
http://imgur.com/x6EfdFC    this is the screnshot after do a AccordionList's hide and show


and for my second question
```
document.addEventListener("backbutton",Codrova_Backbutton, false);
function Codrova_Backbutton(){
  return false
}
```
http://imgur.com/ohXh07r
this is before press backbutton 
every tabs working great and smooth

http://imgur.com/PySG3uv
this is after press backbutton
nav bar and bottom tab disappear

and after I toggle callClose function from phonon.js no.2153
```
// callClose(currentPage, last.page, opts.hashPrefix + last.page + '/' + last.params);
```
Android's backbutton working fine.

By the way, every page have option `preventClose: true` and I had no idea why I can't override Android's backbutton event.

**Comment by John-Henrique** [comment]
You image #book_pic need be height inside of accordion, because when Phonon is ready your image have only width and Phonon calculate size of accordion based in this size. Try leave a height size fixed and give me a feedback.


I don't know, you really need change default action of backbutton? Try this method 😉 

```
document.addEventListener( "backbutton", app_backbutton, false );
	function app_backbutton(){
		if( phonon.navigator().currentPage == 'YOUR_PHONON_HOME_SCREEN' ){
			navigator.app.exitApp();
		}else{
			// Isn't necessary but...
			//history.back();
		}
	}

```

About preventClose
This param sometimes is used incorrectly, use only when user need do an action as save changes or choose an option. When preventClose is true you need add method onClose in your activity like this...

```
activity.onClose(function(self) {
	if(action !== null) {
		self.close();
	} else {
		phonon.alert('Please choose an option.', 'Action required');
	}
});

```
If user take action, you allow to get out using `action = true`. See example in pizza app, into folder examples (Phonon package).

**Comment by ckhsu3926** [comment]
@John-Henrique 
Thanks for your quick reply !
I am sorry about feedback too slowly.

At first I use chrome inspect find the pixel of picture after taken is 437px.
so I make html code like
`<img id="book_pic" style="width:328px;height:437px;">`
Then the AccordionList's view like http://imgur.com/8WOyjAh
What I am looking for is the AccordionList's height fix with inner HTML element.
So I try to do this on camera's callback : 
```
function onSuccess(imageData) {
    BOOK_PIC = imageData;
    document.querySelector('#book_pic').src = "data:image/jpeg;base64," + imageData;
    document.querySelector('#book_pic').style.height = "437px";
}
```
But still didn;t get what I want.
Just curious Is there any solution for this ?

About preventClose , I read the pizza example and learned how to use it.
It's a great function :D

**Comment by Qathom** [comment]
Hi @ckhsu3926,

Thank you for opening this issue and for using Phonon. :)
Did you find a solution?
