### ISSUE TITLE
osVersion is null?

### ISSUE THREAD

**Issue by CKGrafico** [quark-dev/Phonon-Framework#194]
Using ripple on a Mac I have this error (gif)

![Img example](http://i.imgur.com/UrIuWWu.gif)

**Comment by Qathom** [comment]
Hi @CKGrafico,

Thank you for opening this issue.
Can you please give me the output of the following code:
```js
console.log(navigator.userAgent)
```

**Comment by Qathom** [comment]
Please reopen this issue if you still get this error with the latest release **1.4.0**.

**Comment by CKGrafico** [comment]
I will check ASAP
