### ISSUE TITLE
FormData

### ISSUE THREAD

**Issue by CKGrafico** [quark-dev/Phonon-Framework#195]
Why aren't using FormData when post?

**Comment by John-Henrique** [comment]
You is trying do a upload files using AJAX?

**Comment by CKGrafico** [comment]
Nope, I'm trying to do a POST with https://github.com/typicode/json-server and seems that is not working if I don't user Formdata for data

**Comment by CKGrafico** [comment]
Ok was not that... the problem is that on docs you say:

"Default is "application/x-www-form-urlencoded; charset=UTF-8""

but on code I think is application/json no?

**Comment by CKGrafico** [comment]
Yes I can confirm that the error was about docs, now is working
```
phonon.ajax({
            method: method,
            url: url,
            data: data,
            contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
            success: (res) => resolve(res),
            error: (res) => reject(res)
        });
```

**Comment by John-Henrique** [comment]
@Qathom please docs looks like incorrect because default contentType is json.

**Comment by Qathom** [comment]
Hi @CKGrafico and @John-Henrique,

Thank you for opening this issue. It will be fixed.
