### ISSUE TITLE
Component preloader isn't spinning

### ISSUE THREAD

**Issue by John-Henrique** [quark-dev/Phonon-Framework#197]
I'm using Phonon 1.3.5 and saw spinner of preloader isn't spinning... this is happening with you too? Stay stopped, open and close normally.

**Comment by Qathom** [comment]
Hi @John-Henrique,

I don't think so.. pelase, can you give me your complete code so that I can try it?

**Comment by John-Henrique** [comment]
I found the error. I don't remember when, but I put this code in my theme.css and this freeze spinner
```
.circle-progress.active .spinner {
  border-top: 3px solid #19AA93;
  border-right: 3px solid #19AA93;
  border-bottom: 3px solid #19AA93;
  -webkit-animation: circleLoading 900ms infinite linear;
          animation: circleLoading 900ms infinite linear;
}
```
Thanks
