### ISSUE TITLE
iOS problem on loading language files

### ISSUE THREAD

**Issue by yoprogramo** [quark-dev/Phonon-Framework#198]
First, thank you for the framework, I love it.

In a cordova project, the Android version works ok, but in iOS I receive this message: 

"Error: The default locale [res/lang/es.json] file is not found" even when I checked that this file is present (and in Android works), I think is due cross origin requests are only supported for HTTP, not file:/// and it is used on loading the language files.

Do you have some solution for this?

**Comment by gbtux** [comment]
I @yoprogramo 
Did you update your framework version ?
In last versions, I need to use a complete "locale" name for language files : 
*  en-US.json  
*  fr-FR.json  
*  nl-BE.json  
*  nl-NL.json

Can you try this ?
BR //

**Comment by yoprogramo** [comment]
Hello @gbtux 

Yes, it is updated... In fact, I have the es-ES.json file as well, this is my configuration:

```
    i18n: {
        directory: 'res/lang/',
        localeFallback: 'es',
        localePreferred: 'es-ES'
    }
```

I only make it works on iOS with i18n: null ... But Android / browser works good.

**Comment by Qathom** [comment]
Hi @yoprogramo,

Did you try the whitelist with Cordova?
[https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-whitelist/](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-whitelist/).

> By default, navigations only to file:// URLs, are allowed. To allow others URLs, you must add <allow-navigation> tags to your config.xml

**Comment by yoprogramo** [comment]
The problems comes with xmlhttprequest to a file:/// (the language file) that is not permitted on ios... Nothing to do with whitelist.

**Comment by Qathom** [comment]
Maybe this link can help you [Cordova 6 app cannot load from file:// path](http://stackoverflow.com/questions/35754884/cordova-6-app-cannot-load-from-file-path)
Are you using the `WKWebView` plugin?

**Comment by yoprogramo** [comment]
Ummm the only solution seems to use the WKWebView plugin... I'll try, but Telerik's one says not working on cordova-ios-4 and the other seems to works just with cordova-ios-4.1.0

Shouldn't be mentioned this on main page of Phonon? (it does not work with language files on ios unless...) ?
I don't know if it possible, but I would prefer to load the language files in some "compatible" mode...

**Comment by yoprogramo** [comment]
Tried and no luck...

cordova plugin add https://github.com/apache/cordova-plugins.git#master:wkwebview-engine-localhost

XMLHttpRequest cannot load file:///.... Cross origin requests are only supported for HTTP.

Not able to use languages on Phonon in iOs...

**Comment by yoprogramo** [comment]
Just a question... 

Any of you have tried before iOS and i18n with Phonon?

**Comment by yoprogramo** [comment]
I created an -accepted- pull request #205  to avoid the problem. Before closing the issue I left the code of my cordova hook used to create the language.js file needed on ios (supposing you jave the .json files in res/lang):

```
#!/usr/bin/env node
var fs = require('fs');
var path = require('path');

module.exports = function(ctx) {
    console.log("Phonon-ios hook");
    // make sure android platform is part of build
    if (ctx.opts.platforms.indexOf('ios') < 0) {
        return;
    }

	var rootdir = context.opts.projectRoot;
	console.log("Rootdir: "+rootdir);

	var data = createFile (rootdir);
	writeFile(rootdir,data);

};

function createFile (rootdir) {
	var dirLang = path.join(rootdir,"www","res","lang");
	var content = "var langCache = [];\n";
	console.log("Lang directory: "+dirLang);
	if (fs.existsSync(dirLang)){
		console.log("i18n files found");
		fs.readdirSync(dirLang).forEach(function(file){
				var data = fs.readFileSync(path.join(dirLang,file));
				var toadd = "langCache['"+file.replace('.json','')+"']="+data.toString()+";\n";
				content+=toadd;
			});
		return content;
	} else {
		console.log("No language files directory (tpl/lang)");
	}
}

function writeFile (rootdir,data){
	var fileLang = path.join(rootdir,"www","js","language.js");
	fs.writeFile(fileLang,data,function(err){
		if (err) {
			console.log("Error writting file "+fileLang);
		} else {
			console.log("File "+fileLang+" written sucessfully!");
		}
	});
}
```
