### ISSUE TITLE
Component Dialogs add multiple divs

### ISSUE THREAD

**Issue by John-Henrique** [quark-dev/Phonon-Framework#199]
I saw every time when open an alert, a new div is append in body, so clicking on same button (to open alert) 10 times, open 10 divs, but is this expected behavior?
![phonon-alert-divs](https://cloud.githubusercontent.com/assets/332925/22405389/fde82f7a-e628-11e6-9577-12e31ff85828.jpg)

**Comment by Qathom** [comment]
Hi @John-Henrique,

Thank you for opening this issue!
I'll fix this asap! Indeed, the autogenerated dialogs are not removed from the DOM:
