### ISSUE TITLE
[Request] Side Menu 

### ISSUE THREAD

**Issue by alewin** [quark-dev/Phonon-Framework#2]
you can add the side menu? 
responsive ( mobile, tablet ) like this http://codepen.io/ionic/full/cDbFg/

thanks

**Comment by Qathom** [comment]
Hello,

Thank you for your idea.
We will add this type of component in the next release! :)

**Comment by sannysoft** [comment]
That would be great, +1

**Comment by Neotrixsx** [comment]
:+1:

**Comment by Qathom** [comment]
This feature is now available since Phonon v1.0.0!
http://phonon.quarkdev.com/docs/side-panels/
