### ISSUE TITLE
Change page inside a confirm event

### ISSUE THREAD

**Issue by yoprogramo** [quark-dev/Phonon-Framework#201]
I have this code:

```
var confirm = phonon.confirm("¿Enviar identificación?", sitio, true, "SI", "NO");
confirm.on('confirm', function() {
		phonon.navigator().changePage('pagetwo');
} );
```
And does nothing... But if I execute phonon.navigator().changePage('pagetwo'); outside the scope it works... It is normal?

**Comment by John-Henrique** [comment]
I try here and your code is working fine. Please check if you have one pane with ID 'pagetwo'. Check if you have declarated this page in index.html file and if yor app.js file have one action to page two.

You can try visit (on navigator) http://localhost/index.html#!pagetwo (if you is using local server)

**Comment by yoprogramo** [comment]
Yes, I have, in fact is a copy of the Getting Started example (home->page2)... This code is fired inside the where it is processed an asynchronous external event and the user can be viewing any other page in this moment. I know the code is executed, but I still seen the same page.

**Comment by John-Henrique** [comment]
Can you share your code? Only interesting code., please use button isert code.

**Comment by yoprogramo** [comment]
Hello again,

I think I have solved it chaging the preventClose of the other pages to false (previously I had true). Now it is working as expected.

**Comment by John-Henrique** [comment]
To use preventClose you need add activity onClose in your action, without this not work.

**Comment by yoprogramo** [comment]
yes, I know, my onclose was:

```
activity.onClose(function(self) {
            self.close();
    });
```
But now it is working...

**Comment by John-Henrique** [comment]
It's ok, but if your issue is solved, please close this issue.  ;-)

**Comment by yoprogramo** [comment]
Sure... In fact I'm more concern about the ios issue regarding the i18n #198
