### ISSUE TITLE
appending backdrop-panel

### ISSUE THREAD

**Issue by jorgelg** [quark-dev/Phonon-Framework#202]
does this thing has any specific purpose?

![imagen](https://cloud.githubusercontent.com/assets/14224783/22479862/b92defe8-e7c5-11e6-849c-c931a30ea035.png)
(found it on phonon.js)

![imagen](https://cloud.githubusercontent.com/assets/14224783/22480083/92c50714-e7c6-11e6-9b05-6c29fa1c06f9.png)
wild backdrop-pannel div appeared while using side-panel for multiple data-pages and caused me some unexpected behavior while testing...

results in:
![imagen](https://cloud.githubusercontent.com/assets/14224783/22480189/ebe2c3ae-e7c6-11e6-8fd4-544d38eaf75f.png)

commented everything on that function and the error disappeared

**Comment by John-Henrique** [comment]
This is a problem known, #170, #179. But yet not resolved, in #170 you can see one hack to 'resolve' temporarily
