### ISSUE TITLE
Some way to use multiple languages with Phonon on iOS

### ISSUE THREAD

**Issue by yoprogramo** [quark-dev/Phonon-Framework#203]
Once tested that is is not possible to load .json using file:// and XMLHttprequest on iOS... 

What can I do show multiple languages using Phonon?

**Comment by John-Henrique** [comment]
Imagine user entenring first time in app, you can show a screen to choose language or something similar...

After... you refresh page dinamically...
```
languageChoosen = localStorage.getItem( 'language' );
/* ... */
i18n: {
        directory: 'res/lang/',
        localeFallback: languageChoosen',
        localePreferred: languageChoosen +'-ES'
    }
```

I tried this? No, but this is the way... Give-me feedback 👍

**Comment by yoprogramo** [comment]
I tried everything with i18n and iOS (see #198 ), the fact is that is forbidden in iOS (9/10) to load the .json files .. To see my project in iOS I have this in app.js:

```
var i18noptions = null;

if(!!navigator.platform && /iPad|iPhone|iPod/.test(navigator.platform)){
    console.log("ios reduced language");
} else {
    i18noptions = {
        directory: 'res/lang/',
        localeFallback: 'es',
        localePreferred: 'es-ES'
    };
}

phonon.options({
    navigator: {
        defaultPage: 'home',
        animatePages: true,
        enableBrowserBackButton: false,
        templateRootDirectory: './tpl'
    },
    i18n: i18noptions
});
```
Any other think I put in i18n for iS results on error loading .json files. Do you know if someone has used i18n in iOS 9/10 with success?

**Comment by John-Henrique** [comment]
I don't know if someone has used. I never used.

**Comment by Qathom** [comment]
Hi @yoprogramo,

I don't really know iOS, but I read that there is a (new) security mechanism since iOS 9.
According to this [article](http://moduscreate.com/cordova-5-ios-9-security-policy-changes/) and this [stackoverflow thread](http://stackoverflow.com/questions/32706656/ajax-not-working-in-ios-9-0-cordova), you have to use the file called `info.plist` and add exceptions for running requests.

**Comment by John-Henrique** [comment]
@Qathom maybe be interesting update docs about language. What you think?

**Comment by Qathom** [comment]
@John-Henrique It is more linked to native JavaScript than Phonon.
If `info.plist` works, I can add a suggestion in the docs. :)
