### ISSUE TITLE
Component Dialogs - Example of custom dialogs is wrong

### ISSUE THREAD

**Issue by John-Henrique** [quark-dev/Phonon-Framework#208]
**Problem**
In docs of component [dialogs](http://phonon.quarkdev.com/docs/dialogs) the markup of custom dialogs is wrong, this way button and text of button will have the same color.

There is using
`<a class="btn btn-flat primary btn-confirm" data-dialog-close="true">Yes</a>`

**Suggestion**
Is necessary remove `btn-flat`, it's all 👍 
`<a class="btn primary btn-confirm" data-dialog-close="true">Yes</a>`

**Comment by Qathom** [comment]
Hi @John-Henrique,

Thank you for opening this issue and for your suggestion.
The `.btn-flat` has a problem, I am working on it!

**Comment by Qathom** [comment]
Hi again @John-Henrique  ;)

Fixed! Please, reopen this issue if it is not the case for you since **[v1.4.2](https://github.com/quark-dev/Phonon-Framework/releases/tag/v1.4.2)**.

**Comment by John-Henrique** [comment]
@Qathom 
Tested on

Android 4.2 and 6
Android Chome 
Windows Chrome 56

Working fine!
