### ISSUE TITLE
Can't use href="#!my-page" if enableBrowserBackButton: false

### ISSUE THREAD

**Issue by HugoCrd** [quark-dev/Phonon-Framework#21]
Because of 
https://github.com/quark-dev/Phonon-Framework/blob/3aa6ed0e2c06fa893e9b538ed58346333b4ccf06/src/js/core/navigator.js#L600
and 
https://github.com/quark-dev/Phonon-Framework/blob/3aa6ed0e2c06fa893e9b538ed58346333b4ccf06/src/js/core/navigator.js#L762

A link to a page will not work.

**Comment by Qathom** [comment]
I'll fix this asap! Thanks for this observation.

**Comment by Qathom** [comment]
Fixed! If you still get an error, please let me know :)
