### ISSUE TITLE
side panel animations

### ISSUE THREAD

**Issue by jorgelg** [quark-dev/Phonon-Framework#210]
Just wondering... Is it possible to set side-panels to NOT open when swiping screen too close to its side?

**Comment by John-Henrique** [comment]
@jorgelg yes, you can need define data-disable. See [Side panel docs](http://phonon.quarkdev.com/docs/side-panels)

If your case is solved, give us a feedback 👍

**Comment by jorgelg** [comment]
@John-Henrique Yes I saw Side panel documentation before, let me be a little more specific, It seems it was my bad for not explaining it. Let me quote side panel docs : 

> data-disable -  string -	Disable drag and drop from the left or right.

It disables drag and drop from left OR right, what I might need is disable both of them and make the side panel to only open through a button with some JS that I already have.
Thanks in advance for the help

**Comment by John-Henrique** [comment]
Maybe `data-disable="left,right"`?

**Comment by jorgelg** [comment]
I already tried that, same result side panel still opens whenever I swipe

**Comment by jorgelg** [comment]
@John-Henrique at the end of the day I was finally able to disable that swipe thing, at the same time I found out that probably the minimal drag distance to trigger that "swipe to open" thing no matter if the side panel is on the right or left it always takes the distance from left to right

**Comment by John-Henrique** [comment]
Sorry, you got disable drag or not?

**Comment by jorgelg** [comment]
yes sir  :)

**Comment by John-Henrique** [comment]
Share your solution here. In future you solution can help other people 👍

**Comment by jorgelg** [comment]
sure thing, will post about it on saturday, since I would like to share some extra details about that

**Comment by jorgelg** [comment]
Ok... So I've been dealing with side panel's swipe sensitivity, usually that isn't a big deal, but when working with maps, and swiping across it to find a location or anything, having the side panel opening everytime becomes quite annoying, so in order to work around disabling the "swipe to open" animation for side panel I increased a var called minDragDistance (default value is 5) to a high value, that var can be found in "phonon.js" file or "side-panels.js" if you are just adding side panel's script, it's at the line #4378 on my phonon.js file and at line #35 on side-panels.js file
