### ISSUE TITLE
How to make some part of the screen transparent

### ISSUE THREAD

**Issue by yoprogramo** [quark-dev/Phonon-Framework#211]
I'm using cordova-plugin-qrscanner to scan a qr inside the cordova phonon application and I am unable to make some part transparent (is required due the qrscanner is shown behind the webview). The only way I see the camera is making body.style.display='none' but I need to put a visible element over the camera, so I need the body. Do you have some advice on doing a simple page transparent. I have try with  body.style.bacgroundColor='transparent' but it is not enough...

**Comment by yoprogramo** [comment]
Solved!

Just doing the page transparent is enough!

**Comment by John-Henrique** [comment]
`body.style.bacgroundColor` your write wrong the word **background**

You can change to transparent by using CSS like 
```
.body, .your-element {
background-color:transparent;
}
```
