### ISSUE TITLE
Component Navigator method changePage works only with strings

### ISSUE THREAD

**Issue by John-Henrique** [quark-dev/Phonon-Framework#214]
**Scenario**
When you need change a page you just use `phonon.navigator().changePage( 'myPageID', 'someParam' )` this is normal 

**Problem**
When your param is a number (`param = 15`) changePage don't work, but if you use something like this works
`phonon.navigator().changePage( 'myPageID', ''+ param )` 
`phonon.navigator().changePage( 'myPageID', param.toString() )`

**Comment by Qathom** [comment]
Hi @John-Henrique,

Thank you for opening this issue!
I am working on it. :)

**Comment by Qathom** [comment]
Hi @John-Henrique,

Can you tell me if it is fixed since v1.4.2 ?
Thank you!

**Comment by John-Henrique** [comment]
@Qathom 
Tested on
Android 4.2 and 6
Android Chrome
Windows Chrome 56

Working 👍
