### ISSUE TITLE
hello,How do I obtain parameters routing, please? I want to get the content of a page parameter

### ISSUE THREAD

**Issue by zhaojunlike** [quark-dev/Phonon-Framework#218]
How do I obtain parameters routing, please?
I want to get the content of a page parameter

**Comment by zhaojunlike** [comment]
But I want to give the content have parameters
example：<a data-na....='#!cp_type_list/type/1'></a>
the page content:"#!data.jsp?type=$param"
![image](https://cloud.githubusercontent.com/assets/13638996/23336313/13a6ea42-fc07-11e6-88c0-6abdc9b8e3e7.png)

**Comment by zhaojunlike** [comment]
I didn't can be found on the document.
Hope your team can help me

**Comment by John-Henrique** [comment]
See example of #217

**Comment by Qathom** [comment]
Hi @zhaojunlike,

#217 is a good example.

In your app.on scope, add the following code:
```js
	activity.onHashChanged(function( param_1, param_2, param_3  ){

	});
```

Please reopen this issue if it does not work for you.
