### ISSUE TITLE
Library request in CDNJS

### ISSUE THREAD

**Issue by extend1994** [quark-dev/Phonon-Framework#219]
Hi!
I am a member of CDNJS and we got a library request issue cdnjs/cdnjs#9406.
To let the library operate correctly, I want to confirm which file should we host.
Currently, I add all files under `dist`. But there is a file `theme.css` under `css`. Users seem to be able to revise this file to meet their needs. In this case, is it necessary to add this file?
And If we don't need all files under `dist`, please also tell me :)
Reference: cdnjs/cdnjs#10696

Thank you!

**Comment by John-Henrique** [comment]
@extend1994 you is correct, all files in dist are necessary to use individual components or 'phonon.min' to use all components of Phonon. About theme.css, this is a file to custom CSS, so this isn't necessary in CDN because user need change in case he want customize your app views.

Thanks.

**Comment by extend1994** [comment]
@John-Henrique Thanks for quick response and help!
