### ISSUE TITLE
Phonon V 1.4.2 - Dependence of Awesome

### ISSUE THREAD

**Issue by John-Henrique** [quark-dev/Phonon-Framework#224]
**Scenario**
Using Phonon V 1.4.2 I get error on console "The autocomplete component requires Awesomplete dependency.", just by run Phonon (phonon.min.js).

Project no using autocomplete.

**Comment by Qathom** [comment]
Hi again @John-Henrique,

Thank you for opening this issue, it has been fixed in the v1.4.3 ..
