### ISSUE TITLE
How to pass data from page list to a details page

### ISSUE THREAD

**Issue by jsantari** [quark-dev/Phonon-Framework#23]
I'm working with Phonon and Riot and reached a point where I am not sure what to do. I have a list displayed of Topics each which has a unique topic_id. When I load my details I can pickup the id from my uri but the Riot script code will only execute once on the first load. After that no mater what if I go back and pick a different topic it never executes the Riot code again so the data is always the same as the first time. Suggestions?

**Comment by Qathom** [comment]
Hi,

Do you use page events such as create or ready?
Inside of the ready event for example, you can call update() to update your view:
http://riotjs.com/api/#updating

The "ready" event is called when the page is becoming visible to the user (every time), so you can perform your update here.

Hope it solves your problem! Let me know :)

**Comment by jsantari** [comment]
I did figure out that is what I needed to do and I do have it working now, thanks. Is there any way to reference the riot context for the opts? The only way I could figure to do it was in my tag file script to create a global for the tag ie; tagTC = this - so I could update the template from the ready state of the Phonon page through the tagTC.

**Comment by Qathom** [comment]
You can call the update() function with the current context (this) or with the global namespace (riot):
```javascript
this.update() // inside the tag
riot.update() // global update
```

To my knowledge, keeping the tag's context with a global variable is the best thing to do because riot.update() is not "efficient" if we want to update only 1 tag.
Concerning Phonon, it uses a bridge for example to (auto)-update tags (opts + views) when the app language has changed when ```javascript phonon.updateLocale("NEW_LANG"); ``` is called.

To update opts inside tags, a "bridge" has been created called "tagManager".
You can use it because it is register as a public module, so you can trigger events like so:
```javascript
phonon.tagManager.trigger("PAGE_NAME", "EVENT_NAME", "EVENT_PARAMS");
```

For example:
```javascript
phonon.tagManager.trigger("detail", "ready", "hello again");
```

**Comment by jsantari** [comment]
Tried to use your approach in my tag file with hashchanged but have a problem. The first time in req.params has data. If I go back to my topics and select a different topic hashchanged fires but the req.params is undefined. After looking closer at req I see the problem. The first time in req.params has the value and req.action is blank, the second time in req.params is blank and the req.params holds the value.

**Comment by Qathom** [comment]
I also like how Riot names the parameters so I updated this! :)
If the same error is present, please tell me!

```javascript
self.onHashChanged(function(req1, req2, req3) {
    console.log('req1 ' + req1);
    console.log('req2 ' + req2);
    console.log('req3 ' + req3);
 });
```

Thank you for your suggestion.

**Comment by jsantari** [comment]
Thanks. Not sure on the usage? I was using in my riot tag this.on('hashchanged',function(req) { .. })

Tried changing to  this.on('hashchanged',function(req1, req2) { .. })

req1, req2 come back as undefined?

**Comment by jsantari** [comment]
I see what the problem is now. The uri that back uses from mytopics is #!/home which is correct. From topicmessages it uses #!getmytopics1 which is incorrect - the uri used to access the page is actually #!getmytopics/1 - it's dropping the / for some reason.

**Comment by Qathom** [comment]
Oh! I think I just fixed this. Please, can you tell me if it is now working?
Thank you! :)

**Comment by jsantari** [comment]
Looks good - it's working now as it should.
