### ISSUE TITLE
Dragend.js pageDimentions and Tabs

### ISSUE THREAD

**Issue by oksiquatzel** [quark-dev/Phonon-Framework#231]
I have detected a little problem with the setupTabs/setCurrentTab functions and the dragend.js

because of the 10ms timeout in the setupTabs function for the updateIndicator call the 
setCurrentTab call in

`    phonon.tab = function() {
		return {
			setCurrentTab: setCurrentTab,`

is called earlier. 
therefor the updateIndicator call in setCurrentTab is called earlier and the dragend pageDimentions are not set.
fix for this would be to also add a 10ms timeout in setCurrentTab
`window.setTimeout(function() {
        updateIndicator(pageName, tabNumber);
      }, 10);`

**Comment by Qathom** [comment]
Hi @oksiquatzel,

Thank yor for opening this issue.
I close it thanks to [your pull request #232](https://github.com/quark-dev/Phonon-Framework/pull/232).
