### ISSUE TITLE
notification button text not working

### ISSUE THREAD

**Issue by cinohee** [quark-dev/Phonon-Framework#234]
The text of notification button not working
Test case
 phonon.notif('sample text', 3000, true, 'Ok');

The result:  'Cancel' text is not changed to 'Ok'

**Comment by Qathom** [comment]
Hello @cinohee,

Thank you for opening this issue.
I am working on it.

**Comment by cinohee** [comment]
This is one of best framework I have ever seen. Great speed with low weight.
Good work 👍

**Comment by Qathom** [comment]
Hi @cinohee,

The bug has been fixed in v1.4.4.
Please reopen this issue if it is not the case for you!
