### ISSUE TITLE
dist folder missing when installing from npm

### ISSUE THREAD

**Issue by kbariotis** [quark-dev/Phonon-Framework#237]
When I do `npm install phonon`, there is no `dist` folder in `node_modules/phonon` folder thus I can't include them in my code.

Shouldn't they be there?

**Comment by Qathom** [comment]
Hi @kbariotis,

Thank you for opening this issue.
Please, can you try to install the v1.4.5.
This has been fixed!

**Comment by kbariotis** [comment]
Thank you @Qathom. That was it.
