### ISSUE TITLE
Usage of Cordova Backbutton

### ISSUE THREAD

**Issue by Laurent-B** [quark-dev/Phonon-Framework#241]
Hello , great framework but i have a problem with back button, according to the doc I have to put this 'enableBrowserBackButton: true' but it doesn't work at all.
I think we need an example in the doc, can you give me just an example to understand this function?
Do we need to put a listener in all the pages or in the main js file?

**Comment by cinohee** [comment]
Hello.
Sample option : 

phonon.options({

    navigator: {
        defaultPage: 'dashboard',
        hashPrefix: '!', // default #!pagename
        animatePages: true,
        enableBrowserBackButton: true,
        templateRootDirectory: './template',
        defaultTemplateExtension: 'html', // if you use page templates
        useHash: true
    },
    // i18n: null if you do not want to use internationalization
    i18n: {
        directory: 'lang/',
        localeFallback: 'fa-IR',
        localePreferred: 'fa-IR'
    }
}); 

sample back button usage:
<button data-navigation="$previous-page" class="btn pull-right icon icon-right"></button>

**Comment by Laurent-B** [comment]
Ok thanks but I spoke about the hardware back button.
In my main js file
```phonon.options({
    navigator: {
        defaultPage: 'home',
        animatePages: true,
        enableBrowserBackButton: true,
    	templateRootDirectory: './tpl'
    },
    i18n: {
		directory: 'res/lang/',
		localeFallback: 'fr'
    }
});
var realApp = phonon.navigator();
realApp.on({page: 'home', preventClose: false, content: 'home.html'});
realApp.on({page: 'profil', preventClose: false, content: 'profil.html'});
realApp.on({page: 'opticien', preventClose: false, content: 'opticien.html'});

document.addEventListener('deviceready', function(){
    document.addEventListener("backbutton", onBackKeyDown, false);
	function onBackKeyDown(e) {
	   e.preventDefault();
	   alert('Back Button is Pressed!');
	   phonon.navigator().previousPage;
     }
});
```

but still no effect with the hardware back button action. When I press the back button, it exits the application.
Thanks for your help.

**Comment by Laurent-B** [comment]
I have resolved my problem, it was a conflict between the cordova plugin background mode.
Indeed there is an option with this plugin : 
```
cordova.plugins.backgroundMode.overrideBackButton();

```
It disables our back button and keep the app in the background.
So if you have a problem of backbutton, keep thinking in the plugins and be care.
