### ISSUE TITLE
Component Side panel 2 in same screen

### ISSUE THREAD

**Issue by John-Henrique** [quark-dev/Phonon-Framework#243]
**Scenario**
Actually Side panel allow use only one time. Imagine screen 'dashboard' where left I have a side panel of configurations and right I have a side panel of options about info results of query (like a filter).

**Expected**
Way to use 2 side panels at same screen.

**Problem**
At this moment if has 2 side panels  they crash screen, see this image
![phonon-side-panel-error](https://cloud.githubusercontent.com/assets/332925/24674443/cc602988-1951-11e7-871f-bc05f60013ff.png)

**Comment by kserin** [comment]
Fix commit here : https://github.com/kserin/Phonon-Framework/commit/7506d0c8cf56ea8142acd13dcdbd3be1916c625f
