### ISSUE TITLE
Phonon tabs - Selected Tab

### ISSUE THREAD

**Issue by gh-rboliveira** [quark-dev/Phonon-Framework#247]
Hello, I don't know if I should put this here (on Issues) and I'm sorry if it's the wrong place.

I created a tabs layout and I  was trying to catch the current selected tab. I wanted to add a class to the tab-item.
I didn't find anything for it. I came with a small solution but had to change the phonon.js file. 
`var currentSelectedTab = null;`

@updateIndicator:
`
function updateIndicator(pageName, tabNumber) {
      currentSelectedTab = tabNumber;`

and 
`phonon.tab = function() {
		return {
            currentSelectedTab: currentSelectedTab,
			setCurrentTab: setCurrentTab,
            init: function (pageName) {
                pageName = typeof pageName === 'undefined' ? phonon.navigator().currentPage : pageName;
                if(!pageName) {
                    console.error('The page ' + pageName + ' ' + 'does not exists');
                }
                checkForTabs(pageName);
            }
		};
	};`

Now I can access to the currentSelected tab with:
`phonon.tab().currentSelectedTab`

There is any other way of doing it?
Thank you

**Comment by kserin** [comment]
You can also use the onTabChanged callback and store the current selected tab in a variable. Example here : https://github.com/quark-dev/Phonon-Framework/blob/master/examples/components/tabs-example/index.html .

**Comment by gh-rboliveira** [comment]
@kserin Thank you. 
I guess I don't know yet where is the right place to do the things. I'm liking alot of using Phonon but sometimes I get confused of where (and how) should I do the things.

**Comment by John-Henrique** [comment]
@gh-rboliveira Is you problem solved?

**Comment by gh-rboliveira** [comment]
@John-Henrique Yes it's solved, I don't know why I reopened (probably by mistake). I will close it again.
Thank you
