### ISSUE TITLE
No icon on pull-right in header

### ISSUE THREAD

**Issue by jsantari** [quark-dev/Phonon-Framework#25]
I have the following header but the icon does not appear on the right side, icon on left is fine.
```
<header class="header-bar">
 		<div class="left">
            <button class="btn pull-left icon icon-arrow-back" data-navigation="$previous-page">      </button>
            <h1 class="title">Back</h1>
        </div>       
        <div class="center">
            <h1 class="title"><img id="smlogo" src="img/wslogo4.png">WSPR4 Topics {opts.userid}</h1>          
        </div>
        <a class="btn pull-right icon icon-home" data-navigation="login"></a>
    </header>
```

**Comment by Qathom** [comment]
The class **.title** should be unique in the header, please try the following code:

    <header class="header-bar">
            <button class="btn pull-left icon icon-arrow-back" data-navigation="$previous-page"></button>
            <div class="center">
                <h1 class="title"><img id="smlogo" src="img/wslogo4.png">WSPR4 Topics {opts.userid}</h1>          
            </div>
            <a class="btn pull-right icon icon-home" data-navigation="login"></a>
    </header>

**Comment by jsantari** [comment]
Ok, it works now. I mixed header html from the example page two and page one. Didn't know that title had be to be unique. Thanks.
