### ISSUE TITLE
Vue - Cordova -Phonon  issue

### ISSUE THREAD

**Issue by vitoo** [quark-dev/Phonon-Framework#250]
Hi,

I didnt succeed to make work the pizza-app-with-vue example in Cordova

Cordova dont want this line : 
 
`import App from './App'
`
So i've tried to workaround this, finally i got in console error : 

`Cannot read property 'os' of undefined
`

Do you know what's wrong ? Does someone have a cordova - phonon - vue example starter project ?

Thanks

**Comment by qathom** [comment]
Hi @vitoo,

Thank you for opening this issue.
Which Phonon file are you including?
I updated the [Vue example](https://github.com/quark-dev/Phonon-Framework/tree/master/examples/pizza-app-with-vue).
Please, reopen this issue if you need more help!
