### ISSUE TITLE
How to do bottom navigation?

### ISSUE THREAD

**Issue by jet10000** [quark-dev/Phonon-Framework#255]
https://material.io/guidelines/components/bottom-navigation.html

**Comment by John-Henrique** [comment]
Your question is "how to do bottom navigation?"?

**Comment by qathom** [comment]
Hi @jet10000,

Thank you for opening this issue.
You can use [tabs](http://phonon.quarkdev.com/docs/tabs).
If you want to update the content without tabs (no horizontal scroll, etc.), it is better to change the view dynamically.
Please, reopen this issue if I didn't understand your request.
