### ISSUE TITLE
Previous Page not working

### ISSUE THREAD

**Issue by jsantari** [quark-dev/Phonon-Framework#26]
I'm having a problem with Previous Page not working correctly. I have a page with a list on it. Each list item has two links on it to go to one of two pages ie; href="#!messages/1/Topic One" etc. The second link might be href="#!edittopic/1/Topic One. For some reason the previous page sometimes drops the last slash when it tries to navigate ie; href="#!edittopic/1Topic One. At that point the nav is completely out of sync and it doesn't navigate to the right page.

Edited: I've determined that no matter which of the links you use first the second link will produce the error when trying to use $Previous-page

**Comment by jsantari** [comment]
I am guessing that this is related to the change made in the last update? Your thoughts on this?

**Comment by Qathom** [comment]
Thank you for this bug report, I check it now!

**Comment by Qathom** [comment]
You are right!
Thank you so much :)
