### ISSUE TITLE
Angular 1.6.4

### ISSUE THREAD

**Issue by AGhasemzadeh** [quark-dev/Phonon-Framework#262]
Hello,
I want to build application with angular 1.6.4 but when I use it I get empty page and browser stop working.

**Comment by qathom** [comment]
Hi @AGhasemzadeh,

There is an updated [example with Angular2](https://github.com/quark-dev/Phonon-Framework/tree/master/examples/pizza-app-with-angular).
If you need help for your app made with Angular 1.x, please reopen this issue and share some code or showed errors.
