### ISSUE TITLE
i18n().bind(): callback has no parameters

### ISSUE THREAD

**Issue by jkearins** [quark-dev/Phonon-Framework#266]
Callback function is called without parameters in bind():
```
function bind(el, callback) {
       ....
       var callbackFunction = callback;
       ...
                computeNodes(elements, json);
                if (typeof callbackFunction === 'function') callbackFunction();
       ...
                if (typeof callbackFunction === 'function') callbackFunction();
       ...
}

```
So callback is useless. Maybe there should be _json_ parameter?
`                if (typeof callbackFunction === 'function') callbackFunction(json);
`

**Comment by qathom** [comment]
Hello @jkearins,

Thank you for opening this issue.
The `bind()` function retrieves the DOM elements with `data-i18n` attributes and adds the internationalized text. The callback function has no parameters because it only writes attributes and text.

**Comment by jkearins** [comment]
Hm. What can I do in callback function if it has no parameters? 
If I need some keys in script I do:
```
phonon.i18n().bind();
phonon.i18n().getAll(function(json){
	cKey = json['Key'];
});

```
Now cKey has intenationalized value. But getAll() is called twice: in bind() and getAll() itself.
The above code could be simpler:
```
phonon.i18n().bind(null, function(json){
	cKey = json['Key'];
});

```
But bind() does not pass json to callbackFunction().
Are you sure callbackFunction() should not have a parameter?
