### ISSUE TITLE
Cache for json language file seems not working

### ISSUE THREAD

**Issue by jkearins** [quark-dev/Phonon-Framework#267]
If I call:
```
phonon.i18n().bind();
phonon.i18n().getAll(function(json){
...
});
```
the lang file lang/en-US.json retrieves twice from server. It seems like _jsonCache_ does not work correctly. The array _jsonCache_ is not filled during the call of bind() and the following call of getAll() retrieves .json file again.

**Comment by qathom** [comment]
Hi @jkearins,

Thank you for opening this issue.
It has been fixed in the latest version ([v1.4.6](https://github.com/quark-dev/Phonon-Framework/releases/tag/v1.4.6)).
Please, reopen this issue if it is not the case!
