### ISSUE TITLE
Custom Dialog accessing inputs

### ISSUE THREAD

**Issue by jsantari** [quark-dev/Phonon-Framework#27]
If I am using a custom dialog is there a way to directly access input elements (like prompt provides)?

**Comment by Qathom** [comment]
Hi!

No :/, this was designed only for auto-generated prompts.
I think I will make it available asap! :)

**Comment by jsantari** [comment]
Ok. I'm experimenting with a messaging type app and want the user to be able to click a link to open a form to make the post. Can you suggest the best approach for this with Phonon? Maybe a panel? What I am looking to do is open the form, allow them to enter the text and possibly attach an image to upload with the post. Ideally since I am using Riot the best approach would be to be able to mount a tag for this to handle the actions.

**Comment by Qathom** [comment]
Yes, I think that a panel is a good and user-friendly component for your app.
Concerning Riot, I suggest you to use a **nested tag**: http://riotjs.com/guide/#nested-tags.
According to me, it makes the code cleaner (and more logical) by using this.
For example, the tag "messages" (which is the page) has a "write-new-message" child tag.

Hope it helps! :)

**Comment by Qathom** [comment]
I notify you that you can now access input value :)
I forgot to link this issue [#27] in the release.
 
```javascript
var customDialog = phonon.dialog('#custom-dialog');
customDialog.on('confirm', function(inputValue) {
    console.log('confirm! Input value is: ' + inputValue);
});
```
