### ISSUE TITLE
Method to update component created dynamically

### ISSUE THREAD

**Issue by kserin** [quark-dev/Phonon-Framework#271]
Hi,
For some components, a special behavior is bind when the page is loaded, but if the component is created dynamically, this behavior is never bind to the component. For example, it is the case for an input with a floating label. I put a jsfiddle : [https://jsfiddle.net/f9053ehe/2/](https://jsfiddle.net/f9053ehe/2/)
![screen](https://user-images.githubusercontent.com/3446282/32162445-506ccafa-bd59-11e7-987b-d11f338e7c29.png)

If you type something in the second input and then click out of the input, the floating label doesn't stay at the top of the input. It's because the listener was never added for the second input.
It could be great to have a method to add needed listeners (for all components).

**Comment by qathom** [comment]
Hi @kserin,

Thank you for opening this issue.
There is this problem with forms yes!
I read your commit, can you please make a pull request?

**Comment by kserin** [comment]
@qathom Done !

I think the documentation should also be updated. The phonon.forms.update() function should be mentioned

**Comment by qathom** [comment]
Hi @kserin,

Thank you for your contribution!
I updated the documentation and created the release 1.4.7.
