### ISSUE TITLE
Correct way to put internationalized text to var

### ISSUE THREAD

**Issue by jkearins** [quark-dev/Phonon-Framework#273]
If I need some text var in script to be internationalized, I do:
```
phonon.i18n().bind();
phonon.i18n().getAll(function(json){
	cKey = json['Key'];
});

```
Now cKey has intenationalized value. But getAll() is called twice: in bind() and getAll() itself.
The above code could be simpler:
```
phonon.i18n().bind(null, function(json){
	cKey = json['Key'];
});

```
But bind() does not pass json to callbackFunction().
1) Are you sure callbackFunction() should not have a parameter?
2) Is there more correct way to put  internationalized text to var?

**Comment by qathom** [comment]
Hi @jkearins,

The i18n module supports cache, so it won't load the translations again. Your code is fine for your purpose.
Notice that the Phonon v2 is in progress and offers a cleaner module for internationalisation. You can see a preview of the doc [here](https://github.com/quark-dev/Phonon-Framework/blob/dev/docs/core/intl.md).
I would appreaciate hearing your thoughts on this!
