### ISSUE TITLE
Side Panel Bug

### ISSUE THREAD

**Issue by tyrtok** [quark-dev/Phonon-Framework#28]
Error:Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

Using the sample code, trying to navigate between 2 pages using side panel within a single html file.
somehow i am unable to navigate back using the side panel after navigating from the first.

    <div class="side-panel side-panel-left" data-expose-aside="left" data-disable="right" data-page="home" id="side-panel-example">
        <header class="header-bar">
            <button class="btn pull-right icon icon-close show-for-phone-only" data-side-panel-close="true"></button>
            <div class="pull-left">
                <h1 class="title">Side Panel</h1>
            </div>
        </header>
        <div class="content">
            <ul class="list">
                <li><a class="padded-list" href="#!home">Home</a></li>
                <li><a class="padded-list" href="#!pagetwo">Page Two</a></li>
                <li><a class="padded-list">Settings</a></li>
                <li><a class="padded-list">Login</a></li>
            </ul>
        </div>
    </div>

**Comment by Qathom** [comment]
Hello,

Thank you for reporting this issue.
I just fixed it!
