### ISSUE TITLE
Is there a fold panel or group component?

### ISSUE THREAD

**Issue by wuqi** [quark-dev/Phonon-Framework#29]
Is there a fold panel or group component?It is really convenient to show  multiple-choice or other things like that.

**Comment by Qathom** [comment]
I am not sure I understand.
What is the aim? To include components in a quick way with gulp?
For example something like this?
```
gulp build-custom core, panels, dialogs
```

**Comment by wuqi** [comment]
Sorry for my poor english,like this  http://demos.jquerymobile.com/1.4.5/listview-collapsible-item-flat/  Collapsible list items

**Comment by Qathom** [comment]
I see, it is a nice component, I will add it asap!

**Comment by Qathom** [comment]
Since the v1.0.8, we added and named your desired feature "accordion"
Check it out here:
http://phonon.quarkdev.com/docs/accordion

:)
