### ISSUE TITLE
Bug on android when starting app

### ISSUE THREAD

**Issue by ledarky** [quark-dev/Phonon-Framework#292]
Hello
I have a problem with start method. When i try to start application on android device
The method throw an exception ; "The app has been already started"
What is the problem, because on my desktop i don't have this error

i have a init.js file who load the app.js file

// init.js
`if(!ApplicationDemaree) {
      document.body.removeChild(document.querySelector('#app-loader'));       
      ApplicationDemaree = true;
      alert('first loading');
      window.M_APP.start();              
  } else {
        alert('retrying');
  }`

//app.js
`/* global phonon */

phonon.options({
    navigator: {
        defaultPage: 'home',
        animatePages: true,
        enableBrowserBackButton: true,
        templateRootDirectory: './tpl'
    },
    i18n: null //we do not use internationalization
});

window.M_APP = phonon.navigator();

window.M_APP.on({page: 'home', preventClose: false, content: null});

window.M_APP.on({page: 'login', preventClose: true, content: null, readyDelay: 1});
window.M_APP.on({page: 'registration', preventClose: false, content: null, readyDelay: 1});
window.M_APP.on({page: 'settings', preventClose: false, content: null, readyDelay: 1});
window.M_APP.on({page: 'business-details', preventClose: true, content: null, readyDelay: 1});
window.M_APP.on({page: 'boutique', preventClose: false, content: null, readyDelay: 1});
window.M_APP.on({page: 'boutique/nouveau', preventClose: false, content: null, readyDelay: 1});
window.M_APP.on({page: 'chat', preventClose: false, content: null, readyDelay: 1});
`

please can you help me ?

**Comment by John-Henrique** [comment]
Looks like you is calling phonon.start() twice, this need be called only one time.

Why you is using 'content: null'?

**Comment by ledarky** [comment]
hi john
i've found the problem, it is not coming from phonon
i was include cordova plugin crypt on the project
for 'content': null is because i use riot on the project, not the ative templates provided by phonon
