### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Chhekur** [quark-dev/Phonon-Framework#299]
Hii, you didn't provide any way to communicate with you. That's why I choose this  way.
Me and my friend, we are building a platform to build fully featured android app using Node js, Yes Node js.
Then there will be no need to learn android or any other platform.

So what we are thinking, we are selecting your framework as a front end framework for android js.
So we want to collaborate with you if you agree.

Contact me on : 820121223505e@gmail.com

Thanks!

**Comment by qathom** [comment]
Hi @Chhekur, I replied by email, hence, I close this issue.
