### ISSUE TITLE
Flat Menu design?

### ISSUE THREAD

**Issue by tyrtok** [quark-dev/Phonon-Framework#30]
Can I suggest the addition of  flat menu design. something like this...

![screenshot_20151028-131152](https://cloud.githubusercontent.com/assets/12230254/10781201/10dc0326-7d80-11e5-98a6-f6b16482f0dc.png)

**Comment by Qathom** [comment]
Hello,

This kind of menu ("big buttons") looks more like a custom menu than an UI feature.
I prefer to answer for your request like this:

1. I added the support of icons in buttons: you can now add icons in buttons like so

	<button class="btn primary">
		<i class="icon icon-edit"></i>
		Button
	</button>


2. Concerning the button width, it is easy. You can use the CSS property "display: table" or simply "width".

Hope it helps
