### ISSUE TITLE
Documentation site is down

### ISSUE THREAD

**Issue by default-gena** [quark-dev/Phonon-Framework#315]
https://phonon.quarkdev.com/ - 502
Why not to store docs in external service, that can't be down?

**Comment by qathom** [comment]
Hi @Poldan,
Thanks for opening this issue!
The error has been resolved. https://phonon.quarkdev.com is accessible again.
For the moment, phonon v1 is hosted outside of Github Pages - unfortunately, I don't have enough time at the moment to move the v1 documentation, but I take your feedback into account, thank you.
phonon v2 is on Github Pages: https://phonon-framework.github.io/
