### ISSUE TITLE
Dialogs and i18n

### ISSUE THREAD

**Issue by cedced19** [quark-dev/Phonon-Framework#33]
Hi,
I want to change the "ok" and "cancel" label to, for example "oui" and "annuler".
Do I need use custom dialogs or there is a different way to do that.
Is it a defect of Phonon?

Thank you for this powerfull framework.

**Comment by Qathom** [comment]
Hi,

Thank you for your remark.
You can know pass text as argument.
For example:

    phonon.dialog().confirm('text', 'Hello World!', true, 'Oui', 'Annuler');
