### ISSUE TITLE
Static bottom panel and footer

### ISSUE THREAD

**Issue by bonanhel** [quark-dev/Phonon-Framework#34]
Hi,

thank you for this great work!

Is it possible to add a static panel ui component or/and fixed footer.

I think something like notification ui with out timeout bar and close.

Please see bottomed panel with button's at 

http://share.pho.to/9rpem

Thank you.

Kind regards,
Vangelis

**Comment by Qathom** [comment]
Hi,

You can use the style of the "tab" component with/without icons in tab items.

    <header class="header-bar">
        <div class="center">
        <h1 class="title">Top Title</h1>
        </div>
    </header>
    <nav class="tabs">
        <div class="tab-indicator"></div>
        <div class="tab-items">
            <a class="tab-item" >Home</a>
            <a class="tab-item" ><i class="icon icon-edit"></i></a>
            <a class="tab-item" ><i class="icon icon-settings"></i></a>
        </div>
    </nav>
    <div class="content">
        
    </div>

Documentation: [http://phonon.quarkdev.com/docs/tabs](http://phonon.quarkdev.com/docs/tabs)

Hope it helps! :)
