### ISSUE TITLE
Escape preventClose

### ISSUE THREAD

**Issue by cedced19** [quark-dev/Phonon-Framework#35]
I want to use `preventClose`.
But in one case, I don't want to emit the event. For exemple: 
```js
phonon.navigator().changePage('home');
```
Here, it's the application who want to change page not the user. I don't want to emit a event here.

How can I do that?

I think I've to do a condition in the event, but I ask you if there are a better way to do that.

**Comment by Qathom** [comment]
Hi,

Yes, the condition in the event is the good approach.
There is no way to avoid this event if you use preventClose.
