### ISSUE TITLE
loader is required 

### ISSUE THREAD

**Issue by krishnpalchouhan** [quark-dev/Phonon-Framework#36]
this framework is lightest and fastest

but just before loading it looks too bad there must be loader on index page before all

**Comment by Qathom** [comment]
Hey,

Sorry, I am not sure to understand your issue.
Are you trying to force the loading of the default page (home page)?

**Comment by krishnpalchouhan** [comment]
yes we need to show loading  rather then white page for first time

**Comment by Qathom** [comment]
What about an indicator?
```javascript
phonon.indicator("HelloWorld", false);
```
[Documentation API](http://phonon.quarkdev.com/docs/dialogs)
