### ISSUE TITLE
Confirm box cancelable

### ISSUE THREAD

**Issue by tyrtok** [quark-dev/Phonon-Framework#37]
I think i identified some bugs
 var confirm = phonon.confirm('Do you want to APPROVE this transaction?', '', false, "");

1. by default the 'cancelable' seems to be true.

2. if i explicitly declare cancelable false, pressing the 'cancel' button does trigger the on.cancel command but does not close the alert after finish running through. is there anything i missed out?

**Comment by Qathom** [comment]
Thank you for your remark.
Indeed, this was a bug..
I think I just fixed it, please reopen the issue if it is not the case!
