### ISSUE TITLE
Lost param in first access

### ISSUE THREAD

**Issue by John-Henrique** [quark-dev/Phonon-Framework#38]
Every first time when access the 'home' and navigate to 'pagetwo' the param from URL is losted

Error in console: "Uncaught TypeError: Cannot set property 'textContent' of null" this happening because onHashChanged was not fired, but how fix this?

You can see this issue in http://phonon.quarkdev.com/App/public/phonon/examples/pizza-app/ too. First access, no have hash, so need back to home and navigate again to work.

**Comment by Qathom** [comment]
Thank you for reporting this issue.
I just fixed it.
You can now download the latest release [v1.1.0](https://github.com/quark-dev/Phonon-Framework/releases/tag/v1.1.0)

**Comment by John-Henrique** [comment]
lol thank you
