### ISSUE TITLE
Checkbox not working in list with other elements

### ISSUE THREAD

**Issue by John-Henrique** [quark-dev/Phonon-Framework#39]
When added more HTML elements in the li, checkbox don't work. I think that can be accept others elements to allow better li views

```html
<ul class="list">
    <li class="">
        <label class="checkbox">
            <input type="checkbox" class="">
            This works
            <span></span>
        </label>
    </li>
    <li class="">
        <label class="checkbox">
            <input type="checkbox" class="">
            Don't work | Salt - 
            <bold>$ 9.99</bold>
            <span></span>
        </label>
    </li>
</ul>
```

**Comment by Qathom** [comment]
You must put your other tags after <span>

```html
<ul class="list">
    <li class="">
        <label class="checkbox">
            <input type="checkbox" class="">
            This works
            <span></span>
        </label>
    </li>
    <li class="">
        <label class="checkbox">
            <input type="checkbox" class="">
            It should work :) | Salt - 
            <span></span>
            <bold>$ 9.99</bold>
        </label>
    </li>
</ul>
```

Please, reopen this issue if it does not fix your problem.

**Comment by John-Henrique** [comment]
lol

Man how I can contribute to docs of phonon? I'm from Brazil, I can extend docs and translate too

**Comment by Qathom** [comment]
Thank you for your interest :)
I will inform you when the docs will be opened to the public for contribution.

**Comment by John-Henrique** [comment]
Can you create a repo "Phonon Docs"? This is a simple method to allow me contribute with you. Maybe you can create a "organization" here on Github, see https://github.com/organizations/new
