### ISSUE TITLE
Ajax calls

### ISSUE THREAD

**Issue by bonanhel** [quark-dev/Phonon-Framework#40]
Hello,

using Phonon ajax I always get NO_INTERNET_ACCESS.

I test it with Apache cordova and whitelist plugin. I test it also as plain html without cordova, restrictions etc.

Now I am using jQuery ajax instead Phonon Ajax  and everything works fine.

Any idea/help about?

Thanks!

Vangelis Afantenos

**Comment by John-Henrique** [comment]
Hi, in Phonegap you need allow access to 'internet sites', this can be done in Whitelist on Phonegap/Cordova with Android 4++, in other versions you need change the config.xml file to allow access for all sites (*) or specific (URL).

Can you show your Ajax script and config.xml file? Please, use https://gist.github.com

**Comment by bonanhel** [comment]
Hello John-Henrique, 

thanks for the answer. I am using latest Cordova for android/browser with plugin cordova-plugin-whitelist 1.2.0 "Whitelist".

My config.xml has 

    <plugin name="cordova-plugin-whitelist" spec="1" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />

My script is almost same as documentation example : 

				var req = phonon.ajax({
					method: 'GET',
					url:'http://server/restapi.php',
					crossDomain: true,
					data: {action: 'login', username:'test', password: 'test', uuid: '1234', version : '1.0'},
					timeout: 6000,
					success: function(res)
					{
						console.log(res);
					},
					error: function(err)
					{
						console.log('error ' + err);
					}
				});
I also test it with html meta tag : 

http-equiv="Content-Security-Policy" content="default-src *; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'"


Please notice that jQuery ajax calls working fine. Also notice that I have the same problem without cordova using it as web app.

Regardsm
Vangelis

**Comment by Qathom** [comment]
Hello bonanhel,

Thank you for opening this issue.
I think there was an error while checking the status code (2xx = success, error otherwise).
Can you please try the [latest release](https://github.com/quark-dev/Phonon-Framework/releases/tag/v1.1.1)?

Thank you in advance :)

**Comment by bonanhel** [comment]
Yes it's working now.

Thank you for the quick response!

Regards,
Vangelis
