### ISSUE TITLE
XMLHttpRequest does not return status 200 for local files

### ISSUE THREAD

**Issue by PaulRieger** [quark-dev/Phonon-Framework#41]
The following does not work on a device with iOS 9.1 using cordova:
```
if (req.readyState === 4 && req.status === 200) fn(req.responseText);
```
in navigator.js line 394

This is because XMLHttpRequest does not return a status code when accessing local files.

One solution might be to omit the status check and check the responseText string length instead.

**Comment by Qathom** [comment]
Thank you for reporting this problem.
Can you please tell me if it fixed this issue?
https://github.com/quark-dev/Phonon-Framework/releases/tag/v1.1.2

I updated the condition like so:
```javascript
if(req.readyState === 4 && (req.status === 200 || !req.status && req.responseText.length))
```
