### ISSUE TITLE
Lists hidden large texts - small tweek

### ISSUE THREAD

**Issue by John-Henrique** [quark-dev/Phonon-Framework#42]
Tested in mobile with small screen (LG E471F). When the page has a list, the LI with large text are hidden, don't back to next line.

````HTML
<ul class="list">
	<li>
		<p>This is my large large large large largelarge large large large largelarge large large large large text!</p>
	</li>
	<li>
		<p>This is my small text</p>
	</li>
</ul>
````
![screenshot_2015-11-29-10-12-10](https://cloud.githubusercontent.com/assets/332925/11457150/b27ba6ac-9688-11e5-8477-db02212f95b3.png)
![screenshot_2015-11-29-10-51-16](https://cloud.githubusercontent.com/assets/332925/11457151/b27dcdd8-9688-11e5-82cb-1a6b4255e636.png)

**Comment by Qathom** [comment]
Thank you for reporting this, I just fixed it :)
