### ISSUE TITLE
Unable to scroll

### ISSUE THREAD

**Issue by Frehiwet** [quark-dev/Phonon-Framework#43]
Hellow,

I am using Phonon framework on phone gap mobile application. After applied the framework, I am not able to scroll down or up when the page grows. Do you guys have any suggestions on that? 

Thanks

**Comment by John-Henrique** [comment]
What is the version of Phonon that you is using? Please, try [1.1.2 release](https://github.com/quark-dev/Phonon-Framework/releases) and reply this topic again

**Comment by bonanhel** [comment]
Hello,

same problem here using apache cordova.

Touch scroll works only using two fingers.

Regards,
Vangelis

**Comment by Qathom** [comment]
Hello,

Thank you for reporting this!
I just fixed it.. please tell me if it corrects your problem :)
[download the latest release v1.1.3](https://github.com/quark-dev/Phonon-Framework/releases/tag/v1.1.3)

**Comment by bonanhel** [comment]
It's ok now. You are the best! :)

Thank you
Vangelis

**Comment by Qathom** [comment]
:+1:  :)
