### ISSUE TITLE
Side Panels - Horizontal Scroll

### ISSUE THREAD

**Issue by alexmira** [quark-dev/Phonon-Framework#44]
on side panels its possible to horizontal scroll if you hold your finger in the panel, check the video on link

https://mega.nz/#!uMtXgIaB!QqpzC2NV1MfeGn4JduPA9LB9K_3tGIwC1xg7Ka4kFmU

**Comment by alexmira** [comment]
i fixed it with : 

body, html {
	position: fixed;
	width: 100%;
	height: 100%;
	overflow: hidden;
}
body {
	overflow-y: auto;
	height: 100%;
}

**Comment by Qathom** [comment]
Thank you for reporting this issue!
I added the following code:
```
html, body {
    position: relative;
    overflow-x: hidden;
}
```

I successfully tested this fix on Android 5+ (emulator).
Please tell me if it does not fix your problem on your device!
