### ISSUE TITLE
Notifications time out

### ISSUE THREAD

**Issue by bonanhel** [quark-dev/Phonon-Framework#46]
Hello,

notifications with timeout (auto close) are not always working.

Please, see attached screen shot.

First notification opened without progress bar. Second has progress/timeout and working perfectly.
![screenshot_2015-12-10-08-49-59](https://cloud.githubusercontent.com/assets/298048/11708993/731f412a-9f1c-11e5-8ca2-cf6a800fca5e.png)

**Comment by Qathom** [comment]
Thank you for reporting this issue, I will check it asap!

**Comment by John-Henrique** [comment]
This happning with me too, every when I'm using ```` phonon.notif(...) ```` and have more of only one notification to show.

**Comment by Qathom** [comment]
@bonanhel and @John-Henrique 
I reproduced this strange error: the problem is related to the notification creation (inside the DOM).

I push the fix asap!

**Comment by Qathom** [comment]
You can now download the [latest release 1.1.5](https://github.com/quark-dev/Phonon-Framework/releases/tag/v1.1.5)

Please, reopen this issue if you still have the same issue!
