### ISSUE TITLE
.changePage() with similar names

### ISSUE THREAD

**Issue by tyrtok** [quark-dev/Phonon-Framework#47]
Hi,

found a bug, 
For example if i am navigating from notification.html to notificationdetails.html. 
within that page there is a button that invoke .changePage('notification'). 

There will be no response from the code and error.

Problem is solve after i change the the naming from notificationdetails.html > notidetails.html

**Comment by Qathom** [comment]
Hi,

Thank you for reporting this strange issue..
Do you use page templates? If yes, maybe you called the page wrapper "notification" twice?

**Comment by tyrtok** [comment]
I believe i am using page template (class="app-page"  + data-page='true') .
The error occurs when either 1 of the .html's name is a subset of another. 
like notification.html vs notificationdetails.html. The 'notification' is the identical word that exist in these 2 example.

That is what happening to mine though. Hope it helps.

**Comment by Qathom** [comment]
I don't get this issue..
Page contents of the kitchen sink are prefixed with the word "page".
Please, see [kitchen-sink/contents](https://github.com/quark-dev/Phonon-Framework/tree/master/kitchen-sink/contents).

Is the kitchen sink working for you?
