### ISSUE TITLE
events inside tabs not working

### ISSUE THREAD

**Issue by bonanhel** [quark-dev/Phonon-Framework#52]
Hello, I am trying to add event listener inside tab with no luck...

	app.on({page: 'home', preventClose: false, content: 'page-home.html', readyDelay: 1}, function(activity)
	{
		activity.onCreate(function()
		{

			document.querySelector('.statusbtn').on('tap', function()
			{
				phonon.alert('Example', 'Hello');
			});

		});
	});

	<div class="content" data-tab-contents="true" data-disable-swipe="false">
		<div class="tab-content">
			<div class="" id="dashboard">
			</div>
			<nav class="tabs">
				<div class="tab-items">
					<button id="statbtn" class="statusbtn btn fit-parent positive" data-i18n="text: status-free"></button>
				</div>
			</nav>
		</div>
	</div>

**Comment by John-Henrique** [comment]
You need pay attention in your code...

Your problem is, you is using ID in button and add event listener to CLASS. See your code again.

**Comment by Qathom** [comment]
Hello,

@bonanhel : you found a bug, thank you!
The problem: the event (pagecreated) is dispatched **after** the onCreate callback is called, so the UI component (tabs) is not actually ready to use.

**Comment by Qathom** [comment]
You can now download the [latest release 1.1.5](https://github.com/quark-dev/Phonon-Framework/releases/tag/v1.1.5)

Please, reopen this issue if you still have the same issue!
