### ISSUE TITLE
Lists not scrolling in sub pages

### ISSUE THREAD

**Issue by adrianvu** [quark-dev/Phonon-Framework#53]
Hi,

Is anyone facing the issue on lists in sub-pages not able to scroll? The list in the main page works, but when using list in subsequent pages, it is not scrollable. I tested this on iOS Safari and it works fine. But on iOS chrome and adding the web onto homescreen via safari does not work. Any fix to make the page scrollable?

Edit: Tested the kitchen sink, same issues as well.

Thank you!

**Comment by Qathom** [comment]
Hi,

Very strange..
On which version of Chrome for iOS did you test?

**Comment by John-Henrique** [comment]
With me this happening to, when list is created dynamically, appears don`t have height and the page not extend to down... very strange 

Android 4.0.1

**Comment by Qathom** [comment]
Please, can you tell me if it is working now with the latest relase (1.2.0)?
Thanks in advance.

**Comment by John-Henrique** [comment]
this works to me, but sometimes don't work on 'pagetwo'. I don't understand why... (Visa modas = dafault page and Look = pagetwo)

![screenshot_2016-02-16-15-40-46](https://cloud.githubusercontent.com/assets/332925/13085201/24a01dfc-d4c4-11e5-97f4-bb17f6ecb44a.png)

![screenshot_2016-02-16-15-42-06](https://cloud.githubusercontent.com/assets/332925/13085199/2498c3fe-d4c4-11e5-94f3-87fdb9ba07a0.png)

**Comment by Qathom** [comment]
Hi @adrianvu and @John-Henrique,

The latest release should fix your issue!
Please, let me know :)

**Comment by John-Henrique** [comment]
Tested, fixed! :+1:
