### ISSUE TITLE
Bug when using the full panel and notification

### ISSUE THREAD

**Issue by S333** [quark-dev/Phonon-Framework#54]
Hi,
I am using the full panel to create a form. On the left hand-side each label has own text for notification. After clicking the label, notification is shown, and if at this moment I click  the notification, then the whole panel closes.

Thank you.

**Comment by Qathom** [comment]
Hi,

Thank you for reporting this issue. I will check this problem asap.

**Comment by Qathom** [comment]
The latest release fixes this issue, please reopen this issue if it is not the case for you!

**Comment by S333** [comment]
Thank you very much.
Downloaded the new release,  checked, all it works.

Antho Meiz <notifications@github.com> �����(�) � ����� ������ Mon, 04 Jan  
2016 17:58:19 +0200:

> The latest release fixes this issue, please reopen this issue if it is  
> not the case for you!
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/quark-dev/Phonon-Framework/issues/54#issuecomment-168715078


-- 

Best regards,
  Sergey Shevchenko
