### ISSUE TITLE
touch event issue on "qqbrowser"

### ISSUE THREAD

**Issue by lloydzhou** [quark-dev/Phonon-Framework#55]
if using dialog ui in "qqbrowser", when dialog closed, the "tap" event can not working. i touch anything, no effect.

**Comment by Qathom** [comment]
I don't know qqbrowser.. Is it a webkit based browser?

**Comment by John-Henrique** [comment]
@lloydzhou qqbroswer from java2me?

**Comment by lloydzhou** [comment]
may by qqbrowser based on webkit...
i using it in android, the package name is "com.tencent.mtt".

the close button of panel have the same issue.

**Comment by Qathom** [comment]
Hi @lloydzhou,

Does the latest release fix your issue?
Thanks in advance.
