### ISSUE TITLE
tabs bottom and pin bottom class

### ISSUE THREAD

**Issue by labac1603** [quark-dev/Phonon-Framework#56]
plz add it :+1: 
+ tabs bottom 
+ pin div bottom

**Comment by Qathom** [comment]
You can put bottom tabs like this:
```
    <nav class="tabs">
        <div class="tab-indicator"></div>
        <div class="tab-items">
            <a class="tab-item" >Home</a>
            <a class="tab-item" ><i class="icon icon-edit"></i></a>
            <a class="tab-item" ><i class="icon icon-settings"></i></a>
        </div>
    </nav>
```

**Comment by labac1603** [comment]
thanks, but how to use phonon.navigator() to get id of page.
eg: /#!pagedialog/123 , got id = 123

**Comment by Qathom** [comment]
To get the current page name:
```javascript
var pageName = phonon.navigator().currentPage;
```

Hope it helps ;)

**Comment by labac1603** [comment]
thank you :+1: , but can i use this like GET method on browser? :smile:

**Comment by John-Henrique** [comment]
You can use phonon.onHashChange( var1 ) please see first page of docs or in app example

**Comment by John-Henrique** [comment]
http://phonon.quarkdev.com/#getting-started see example app.js

**Comment by labac1603** [comment]
thanks @John-Henrique, phonon's docs difficult to see and it's unintelligible :cry:
