### ISSUE TITLE
Tabs on chrome browser not full width

### ISSUE THREAD

**Issue by labac1603** [quark-dev/Phonon-Framework#57]
Tabs on chrome browser not full width.
Fixed: 
phonon.css line 654
```
.expose-aside-left .tabs {
    width: 100%; /*72%;*/
    /*left: 28%;*/
  }
```

**Comment by John-Henrique** [comment]
This problem is happening only in chrome? What`s you version of chrome and phonon?  I use last version and works fine to me...

**Comment by labac1603** [comment]
i use last version :smile:

**Comment by labac1603** [comment]
And How to add more icon? :lollipop:

**Comment by John-Henrique** [comment]
.icon-labac1603 {
/* your rules */
}

**Comment by Qathom** [comment]
Thank you!
Just fixed..
