### ISSUE TITLE
material design

### ISSUE THREAD

**Issue by badpenguin** [quark-dev/Phonon-Framework#58]
Wich is the correct way to change the colors for material design?
do i need to hack the stylus file that holds the colour's datas?

**Comment by John-Henrique** [comment]
You need change CSS rules (in other file like myStyle.css). You can use Chrome console to see what is the rules to change style of specifics elements.

Example to header bar
.header-bar {
    background-color: #0084e7;
    border-bottom: 0 solid #2e2bc9;
 }

**Comment by Qathom** [comment]
**Stylus**: you can specify your style by changing the value of variables contained in the (https://github.com/quark-dev/Phonon-Framework/blob/master/src/stylus/_variables.styl)[_variables.styl] file.

I will add a CSS file to change the style without preprocessors asap.
For the moment, you can change the style like @John-Henrique suggests.
You can also fin the elements you use in (https://github.com/quark-dev/Phonon-Framework/blob/master/dist/css/phonon.css)[phonon.css]

**Comment by Qathom** [comment]
@badpenguin You can now customize this CSS file [theme.css](https://github.com/quark-dev/Phonon-Framework/blob/master/dist/css/theme.css)
