### ISSUE TITLE
Phonegap - on Android devices external HTML files are not working

### ISSUE THREAD

**Issue by hunbubu** [quark-dev/Phonon-Framework#6]
On Android devices (tested in  external HTML files are not working as pages on Phonegap apps. When they are inserted to index.html everything works well. On IOS devices and desktop browsers it's working fine.

Tests were run with the offical Phonegap android and IOS apps.

**Comment by Qathom** [comment]
Did you use a "page wrapper" in your external HTML file?
On which Android version is it not working? On Android 4.2 + 4.4, it is working well on my devices (Samsung Galaxy S3 + Mini).

In your index.html file:
`<mypage data-page="true"></mypage>`

In your mypage.html file:

`<mypage class="app-page"> 
    <header class="header-bar">
        <div class="center">
            <h1 class="title">Hello!</h1>
        </div>
    </header>
    <div class="content">...</div>
</mypage>`

**Comment by hunbubu** [comment]
I have run some more tests:

Yes, I have used page wrapper in my external HTML files. It works well in desktop browsers, on IOS with PhoneGap testing app. It works in Android too when I build the app, only fails in PhoneGap testing app on Android, so it's not critical for us, only takes a bit more development time.

Anyway it's a great and lightweight framework and thanks for making and sharing it.

**Comment by Qathom** [comment]
Thank you! :)
I will check it asap. Maybe, if you start the app after the OnDeviceReady event, it can fix this issue.

´´document.addEventListener('deviceready', function() {
    phonon.navigator().start();
}, false);´´

**Comment by Danjavia** [comment]
Same issue here i put the code and  continue without function it.

**Comment by Qathom** [comment]
I tested on Android 4.4 with Cordova (Phonegap) and it is working..
Can you please give me more information (which Android version did you use) ?
Do you get an error in the logcat ?

Thanks!

**Comment by Danjavia** [comment]
android 5.0 and no emit erros

**Comment by Qathom** [comment]
Ok. I'll check it asap with an emulator.

**Comment by hunbubu** [comment]
The phone I've tested on and not worked with PhoneGap testing app.
Samsung Galaxy Note 2 - Android 4.4.2

**Comment by Danjavia** [comment]
@hunbubu +

**Comment by Qathom** [comment]
Hello,

I tested the kitchen sink with Cordova (v5.3.3) on:
* Samsung Galaxy S3 running Android 4.4
* Emulator running Android 4.4
* Emulator running Android 5.0

I can not reproduce your error.. :(
One idea: can you please give me a light example of a Phonon app that is not working with Cordova?

**Comment by krishnpalchouhan** [comment]
not working on t2 ultra

uncaught typeerror cannot read property 'appendchild' of null

**Comment by krishnpalchouhan** [comment]
some time after creating apk its working

**Comment by Qathom** [comment]
@krishnpalchouhan : please can you give me the line number of the error "appendchild of null" and the filename you're using?
Thanks in advance!

**Comment by krishnpalchouhan** [comment]
no line no type thing



Please let me know if you need more information.

*Thanks and Regards*
*Krishnpal singh Chouhan *

*Ebullience Tech. | www.ebullience-tech.com
<http://www.Ebullience-tech.com>*


*Cell: +91-9826949593*

**Comment by krishnpalchouhan** [comment]
no such line no..
just look at screen capture
PFA!

Please let me know if you need more information.

*Thanks and Regards*
*Krishnpal singh Chouhan *

*Ebullience Tech. | www.ebullience-tech.com
<http://www.Ebullience-tech.com>*


*Cell: +91-9826949593*

**Comment by niravpatel2008** [comment]
I have also same issue.
I just have downloaded pizza example and added corodova.js (Version 3.X.X) and its stop working after reading this bug i tried to adding content to main file index.html and its work like charm.


Framework should have ability to load external file as it will help a lot to developer to code structuring.

**Comment by krishnpalchouhan** [comment]
At android it's not working while development it just shows White window no error nothing

Mobile xperia t2 ultra
 Screen size 6.0
Android OS 5.1.1

But after creating apk it start working

**Comment by Qathom** [comment]
@krishnpalchouhan or @niravpatel2008 : could you send me a zip folder so that I am sure to work on a not working app :/
If you get the same error with "appendchild": I am pretty sure that you use an UI component before "Phonon Core" is actually ready. If it is the case, the following code should fix your issue:

```javascript
phonon.onReady(function() {
    //...
} );
```

**Comment by niravpatel2008** [comment]
@Qathom Thanks a lot.

Please find .zip link of sample app (https://drive.google.com/file/d/0ByiUVH6GGz1mbjF2SGlyRDF0Rnc/view?usp=sharing)

Some ques
- Also is there any way in framework ajax function to add set xhr header?
- I want to add side-panel accessible from all pages is there any way as right now i can open from home page only.

**Comment by Qathom** [comment]
@niravpatel2008 : does the phonon.onReady fix your issue?
Thank you for sharing your zip folder.

* I just added the support of **custom headers** (please download the latest release - v1.0.9). ajax documentation: http://phonon.quarkdev.com/docs/ajax
* About **side panels accessible from all pages**: this is not possible right now, but I will fix this asap :)

**Comment by niravpatel2008** [comment]
@Qathom 

I have tried phonon.onReady but it does not fixed. 

my suggestion please add one sample app with cordova.js/phonegap.js with structure in doc link of your site so everyone can boost start from there. 

Also i will suggest you about improvement in this coolest project. i really like your phonon framework.
