### ISSUE TITLE
Documentation: copy paste work :)

### ISSUE THREAD

**Issue by Smile4ever** [quark-dev/Phonon-Framework#61]
At http://phonon.quarkdev.com/docs/utility we see:

Text Alignment
Left Aligned

Use the .text-left class on the element.
Center Aligned

Use the .text-left class on the element.
Right Aligned

Use the .text-left class on the element.
Justify Aligned

Use the .text-left class on the element.

Looks like someone forgot to change the class names.

**Comment by John-Henrique** [comment]
little mistake, will be fixed in next version of docs...

**Comment by Qathom** [comment]
Fixed. Thank you :)

**Comment by John-Henrique** [comment]
Last remaining http://phonon.quarkdev.com/docs/utility
Right Aligned
Use the ```` .text-rught ```` class on the element.

**Comment by Qathom** [comment]
Thanks.. :+1:
