### ISSUE TITLE
Using indicator captures click events

### ISSUE THREAD

**Issue by amtgard** [quark-dev/Phonon-Framework#62]
After creating an indicator, the .close() method leaves trash in the DOM which captures click events.

Setup:
I'm using jquery selectors with on('click', '.class-name') in order to capture events from several DOM nodes with the same class selector, because phonon's document.querySelector('.class-name').on('tap') only appears to capture events from the first instance of each class in the DOM.

Steps:
Call phonon.indicator();
Call phonon.close();

Results:
phonon.indicator() leaves a full-page node with opacity set to 0, which captures all subsequent click events.

**Comment by John-Henrique** [comment]
Can you paste your code to analyse? Please use https://gist.github.com/

**Comment by amtgard** [comment]
I'll have to set up something to show this, which will take a while.

**Comment by LucasBurg** [comment]
Hy, I thing that Phonon load html in side of root tag e.g <home> <pagetwo>, but It don't clean the nodes of page after, when the user change page or event something.

**Comment by sabatesduran** [comment]
I have the same issue.

This is my code:
```javascript
function getData(id) {
    var indicator = phonon.indicator('Loading', false);

    phonon.ajax({
        method: 'POST',
        url: 'http://webservice.url',
        data: {id: id},
        dataType: 'json',
        success: function(res, xhr) {
           // do stuff
        },
        error: function(res, flagError, xhr) {
             // do stuff
        }
    });
    indicator.close();
}
```
I execute this function in:
```javascript
activity.onReady(function() {
    getData();
});
```

**Comment by sabatesduran** [comment]
I tried to delete the div with the class ```backdrop-dialog```after ```dialog.close();``` but it doesn't work.
When i remove it, the elements with ```data-navigation``` don't change the page and the backButton doesn't work too.

**Comment by Qathom** [comment]
Hello @amtgard , @sabatesduran, @LucasBurg,

Thank you for reporting this.
I am working on it.
It will be fixed in the next release 1.2.2 (coming asap).

**Comment by Qathom** [comment]
Please, reopen the issue if it does not work for you.

**Comment by sabatesduran** [comment]
Doen't work for me.
