### ISSUE TITLE
Phonon with Vue js

### ISSUE THREAD

**Issue by jsantari** [quark-dev/Phonon-Framework#63]
Love what you have done with Phonon - tried it out with Riot and it works pretty well. Have you or anyone every used Phonon with Vuejs? Would love to see an example of this.

**Comment by Qathom** [comment]
@jsantari : I forgot to notify you, but the [example with VueJS is available](https://github.com/quark-dev/Phonon-Framework/tree/master/examples/pizza-app-with-vue)

**Comment by sanchezandoni** [comment]
Can't find the example any where. Is it available somewhere now?

**Comment by BafS** [comment]
For v1 it's here https://github.com/quark-dev/Phonon-Framework/tree/v1/examples/pizza-app-with-vue
