### ISSUE TITLE
Autocomplete input

### ISSUE THREAD

**Issue by alexmira** [quark-dev/Phonon-Framework#65]
I was wondering if you can add in this framework the Autocomplete input feature like jquery mobile have

http://demos.jquerymobile.com/1.4.5/listview-autocomplete/

grats for this amaizing framework

**Comment by John-Henrique** [comment]
This is very easy to do

I did this now, I don't test, see [my autocomplete example](https://gist.github.com/John-Henrique/6b23cb89aa75899e5022)

**Comment by alexmira** [comment]
I was talking about autocomplete with local data where we load the data by ajax and with "keypress" envent, the <li> tags show and hide for what i am writing, with contains filter

**Comment by John-Henrique** [comment]
It's not what you look for, but right now, we have this from HTML 5. You can add a few options case need use params, see examples

```` html 
<input type="text" id="search" list="datalist1" placeholder="Search cars...">
<datalist id="datalist1">
    <option value="Acura" data-url="http://google.com">
    <option value="Audi" data-id="345">
    <option value="BMW">
    <option value="Cadillac">
    <option value="Chrysler">
    <option value="Dodge">
    <option value="Ferrari">
    <option value="Ford">
    <option value="GMC">
    <option value="Honda">
    <option value="Hyundai">
    <option value="Infiniti">
    <option value="Jeep">
    <option value="Kia">
    <option value="Lexus">
    <option value="Mini">
    <option value="Nissan">
    <option value="Porsche">
    <option value="Subaru">
    <option value="Toyota">
    <option value="Volkswagen">
    <option value="Volvo">
</datalist>
````

**Comment by alexmira** [comment]
yes i know, i am using at the moment, but the autocomplete like we have on jquery mobile / kendoui performs better on user experience in Mobile.

I did this with an iframe inside a page of phonon and worked fine, but I am just suggesting for a feature if its possible to do, would be nice :)

**Comment by John-Henrique** [comment]
It's ok... soon will be added

**Comment by BafS** [comment]
@John-Henrique Mais tg

**Comment by BafS** [comment]
@John-Henrique Really? Nice, do a push request when it's finished please :)

**Comment by John-Henrique** [comment]
@BafS Yes  :+1:

**Comment by John-Henrique** [comment]
@alexmira @BafS @Qathom pr waiting :walking:

**Comment by Qathom** [comment]
@John-Henrique Thank you for your contribution :)
```phonon.autocomplete(...)``` is a nice way to deal with this feature

I just merged your pull request and modified some files.
I will change the default style asap (which does not fit with Phonon's style).

**Comment by John-Henrique** [comment]
@Qathom no problem... I waiting for repo to help in docs too

**Comment by Qathom** [comment]
The "open" docs will come asap :)

**Comment by alexmira** [comment]
works like a charm !!!

really nice

**Comment by John-Henrique** [comment]
@Qathom hey bro, this component need something to be published as Phonon's component?
