### ISSUE TITLE
How to add slide panel any page?

### ISSUE THREAD

**Issue by labac1603** [quark-dev/Phonon-Framework#67]
How to add slide panel any page?

**Comment by John-Henrique** [comment]
Hi @labac1603, do you want add SIDE PANEL? That too works on swipe right like slide, see [Component Side Panel](http://phonon.quarkdev.com/docs/side-panels)

**Comment by labac1603** [comment]
@John-Henrique  Does phonon have template engine?

**Comment by Qathom** [comment]
Phonon can load external HTML files as page content only.
You are free to use your favorite template engine or design pattern such as Mustache, Handlebars, Riot, VueJS, etc.

Mustache, Handlebar (for example): use ```<script>``` templates, so you should include them at the bottom of your index.html file.

``` javascript

// use content if you want to
app.on({page: 'pagename', content: 'mypage.html'}, function(activity) {
    
    // this scope is called once the page content is contained inside the page tag

    activity.onCreate(function() {
        // Here you can perform your template logic (once) or perform your logic inside onReady
    });

    // other activity events go here
});
```

Hope it helps :)
