### ISSUE TITLE
Succesive dialogs losing hook to .on ?

### ISSUE THREAD

**Issue by tsauther** [quark-dev/Phonon-Framework#68]
Great product!  Stoked about how well it is integrating with Apache-Cordova in Visual Studio.

I seem to have an issue where a custom dialog, when opened a second/successive time(s), isn't calling the .on('confirm') or .on('cancel') functions.  All is OK on the first open, fails on the 2nd + attempt.  Is this a bug (mine or yours), is my approach wrong, or is there a different control I should be using?

Any pointers are much appreciated!  Thanks in advance.
``` javascript
Open function (edited):
var DialogActions = (function () {
    var DIALOG = phonon.dialog('#page_dialog');  //tried declaring the dialog outside this function-- more globally -- same results
    function DialogActions() { }
    DialogActions.prototype.pauseworkout = function () {
        try {          
            if (document.getElementById('txtPause').innerText == 'PAUSE') {
                DIALOG.open();
            } else {
                document.getElementById('txtPause').innerText = 'PAUSE';
                TimeFunctions.prototype.start();
            }
        } catch (e) {
          console.log(e);
        }
    };
    DIALOG.on('confirm', function () {
        document.getElementById('txtPause').innerText = "RESUME";
    });
    DIALOG.on('cancel', function () {
        document.getElementById('txtPause').innerText = "PAUSE";
        //stop the program here
    });
    return DialogActions;
})();
```

``` html
Dialog HTML:  (Text content edited dynamically)
<body>
    <div class="dialog" data-cancelable="false" data-dialog-id="page_dialog" id="page_dialog">
        //tried this with and without data-dialog-id
        <div class="content">
            <div class="padded-full">
                <h3 id="dialogTitle">Hey! <i class="icon icon-info-outline"></i></h3>
                <p id="dialogQuestion">Do you like chocolate?</p>
            </div>
        </div>
        <ul class="buttons primary">
            <li><a id="btnDialogTrue" class="btn btn-flat positive btn-confirm" data-dialog-close="true">YES</a></li>
            <li><a id="btnDialogFalse" class="btn btn-flat negative btn-cancel" data-dialog-close="true">NO</a></li>
        </ul>
    </div>
......
```

**Comment by Qathom** [comment]
I am not sure to understand the purpose of your function ```Open```.
This function contains a ```class``` but only the constructor is called and the function returns nothing (```void```)

**Comment by tsauther** [comment]
Ok, javascript function syntax aside, I put the code in a more traditional javascript structure(below) and the issue still exists.  You open a dialog the first time and .on('confirm') and .on('cancel') both fire.  You open the dialog a second time and the .on callbacks are not being triggered.

Do I have a javascript error below?

var DIALOG = phonon.dialog('#page_dialog');
function openDialog()
{
    document.getElementById('txtPause').className = document.getElementById('txtPause').className + ' popcolor';
    if (document.getElementById('txtPause').innerText == 'PAUSE') {
        TimeFunctions.prototype.stop();
        setDialogText('Do you want to pause or stop?', '', 'PAUSE', 'STOP');
        DIALOG.open();
    } else {
        document.getElementById('txtPause').innerText = 'PAUSE';
        TimeFunctions.prototype.start();
    }
}

DIALOG.on('confirm', function () {
    document.getElementById('txtPause').innerText = "RESUME";
    DIALOG.close();
});
DIALOG.on('cancel', function () {
    document.getElementById('txtPause').innerText = "PAUSE";
    //stop the program here
    DIALOG.close();
});

**Comment by LucasBurg** [comment]
I am analyse

```javascript
var DIALOG = phonon.dialog('#page_dialog');

function openDialog() {
    document.getElementById('txtPause').className =    document.getElementById('txtPause').className + ' popcolor';
    if (document.getElementById('txtPause').innerText == 'PAUSE') {
        TimeFunctions.prototype.stop();
        setDialogText('Do you want to pause or stop?', '', 'PAUSE', 'STOP');
        DIALOG.open();
    } else {
        document.getElementById('txtPause').innerText = 'PAUSE';
        TimeFunctions.prototype.start();
    }
}

DIALOG.on('confirm', function () {

    document.getElementById('txtPause').innerText = "RESUME";
    DIALOG.close();
});

DIALOG.on('cancel', function () {
    document.getElementById('txtPause').innerText = "PAUSE";
    //stop the program here
    DIALOG.close();
});
```

**Comment by Qathom** [comment]
Hi,

Does the latest release fix your issue?
I could not reproduce your problem..
Thanks in advance.
