### ISSUE TITLE
Component dialogs

### ISSUE THREAD

**Issue by John-Henrique** [quark-dev/Phonon-Framework#69]
I try open a custom dialog by directly and works but with positioning errors.
````html
<div class="dialog" data-cancelable="false" id="my-dialog">
    <div class="content">
        <div class="padded-full">
            <h3>Hey! <i class="icon icon-info-outline"></i></h3>
            <p>Do you like chocolate?</p>
        </div>
    </div>
    <ul class="buttons">
        <li><a class="btn btn-flat primary btn-confirm" data-dialog-close="true">YES</a></li>
        <li><a class="btn btn-flat negative btn-cancel" data-dialog-close="true">NO</a></li>
    </ul>
</div>
````

````javascript
phonon.dialog('#my-dialog').open();
````

If use documented method works fine.
````javascript
myDialog = phonon.dialog('#my-dialog');
myDialog.open();
````
I this case I don't need manipulate dialog dynamically, it's will open only one time.

**Comment by Qathom** [comment]
On which browser/OS version are you running this code example?

**Comment by John-Henrique** [comment]
This case (and others reported issues) was tested in Android 4.1.2 with small screen 320 x 480 px. In the first time (on open) don't work, but in second, works fine.

**Comment by LucasBurg** [comment]
The id's div element is  custom-dialog, then you use this below.
```
phonon.dialog('#custom-dialog').open();
```

**Comment by John-Henrique** [comment]
@LucasBurg thanks, but there is only a example, isn't the real code... (try run to see)

**Comment by Qathom** [comment]
@John-Henrique : please, can you telle me if it works now (since 1.1.8 according to #83) ?

**Comment by John-Henrique** [comment]
Don't working, now a overlay is blocking tap events. Tested in Android 4.0.1, Windows 10 Firefox and Chrome
![screenshot_2016-02-16-20-39-18](https://cloud.githubusercontent.com/assets/332925/13093680/de80a81c-d4ed-11e5-8b94-fa7a4dd12911.png)

**Comment by Qathom** [comment]
Should be fixed now..
The reason is that `gulp cssnano` optimizes zindex values by reducing them.

**Comment by John-Henrique** [comment]
@Qathom fixed now.

**Comment by Qathom** [comment]
:+1:
