### ISSUE TITLE
Component tabs - Little mistake on 320px 

### ISSUE THREAD

**Issue by John-Henrique** [quark-dev/Phonon-Framework#70]
Testing my apps in small screens found this error with tabs (look in tabs title), the shadow not working correctly

**Portrait**
![screenshot_2016-01-08-00-19-03](https://cloud.githubusercontent.com/assets/332925/12188607/195e1ce0-b59e-11e5-8730-0006236100c6.png)

**Landscape**
![screenshot_2016-01-08-00-19-12](https://cloud.githubusercontent.com/assets/332925/12188982/40ccd82c-b5a1-11e5-89df-1f7908be1037.png)

**Comment by Qathom** [comment]
It is because of the title length..
I will change some properties in CSS in order to avoid this :)

**Comment by John-Henrique** [comment]
Works fine. Fixed  :+1:
