### ISSUE TITLE
Component notifications - Lost 'preloader' and freeze

### ISSUE THREAD

**Issue by John-Henrique** [quark-dev/Phonon-Framework#73]
When using component notif every time they freezes on the screen, no preloader appears. See this image

````javascript
phonon.notif( "my message", 10000, true );
````

First time
![screenshot_2016-01-08-21-29-56](https://cloud.githubusercontent.com/assets/332925/12212245/49772dca-b64f-11e5-9246-7e5c4d8afeba.png)

When others notifications are displayed or when click in 'cancel' button (new notifications are shown)
![screenshot_2016-01-08-21-43-00](https://cloud.githubusercontent.com/assets/332925/12212374/daa61e18-b650-11e5-81e9-5b6462b8366d.png)

**Comment by Qathom** [comment]
Thank you for reporting this issue.
Unfortunately, I am buy these days, but I will check this asap! :)

**Comment by Qathom** [comment]
I am back and I just fixed it! Thank you for reporting this. :)
I'll build a release asap.

**Comment by John-Henrique** [comment]
Don't work to me... the problem yet continues.
And changes of #75 are losted :cry:
