### ISSUE TITLE
Can i use it with android 2.3 or what polyfill to support it 

### ISSUE THREAD

**Issue by anaksinar** [quark-dev/Phonon-Framework#74]
This is a nice and fast, i love the ui. Can i use it for android 2.3 and above, If cannot is there any polyfill to support it?

**Comment by John-Henrique** [comment]
Yes, you can use for Web, Android, IOs, Windows phone (and others platforms) because Phonon is a UI framework, so is allowed for all.

**Comment by anaksinar** [comment]
Ok i will use it, i ask this because at phonon site, it says it will compatible with android 4.1

**Comment by John-Henrique** [comment]
Well, is the version of Android 'in use' actually (Android 4) :wink:

**Comment by Qathom** [comment]
@anaksinar : I think you can try Phonon on Android 2.3, BUT versions < 4.0 are known to be slower than the recent versions of Android.
Furthermore, Android < 4 concern 3.2% of androphones only.(http://developer.android.com/about/dashboards/index.html)[http://developer.android.com/about/dashboards/index.html]
