### ISSUE TITLE
can the navigator using pushState API?

### ISSUE THREAD

**Issue by lloydzhou** [quark-dev/Phonon-Framework#76]
can the navigator using pushState API?

**Comment by John-Henrique** [comment]
Well, Phonon don't use pushState, but this is an API from HTML5, then, you can use ````history.pushState(state, title, url);```` if you need.

See docs from [History HTML5](https://developer.mozilla.org/en-US/docs/Web/API/History/pushState#JavaScript)

If this isn't what you want know, please, give me a example of you want use this... :sweat_smile:

**Comment by lloydzhou** [comment]
i using with riotjs. so i write  one tag to replace the functional of navigator.js https://gist.github.com/lloydzhou/f4742146942247302103

1. using riot.route, can route url with  pushState API
2. create animate by change the class of DOM.

so, i build phonon without "i18n.js", "navigator.js", "public.js" and "tagmanager.js". the size of "phonon-core.js" only 7.8k

**Comment by Qathom** [comment]
If you want to use navigator without the hash tracking:

````javascript
phonon.options({

	navigator: {
	    defaultPage: 'home',
	    hashPrefix: '!', // default #!pagename
	    animatePages: true,
	    enableBrowserBackButton: true,
	    templateRootDirectory: '',
	    useHash: false // disable hash tracking
	},
	i18n: null
});
```
