### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by Ahmadbaba46** [quark-dev/Phonon-Framework#77]
I use this framework on different browsers but only chrome support it. Any solution? Thanks.

**Comment by John-Henrique** [comment]
I just tested in Chrome, Internet Explorer and Firefox works fine. Can you tell me what exacly not working?

Tip: When you run **phonegap run browser** your SO will call the principal browser, so you need open Firefox (eg) and tipe URL *http://localhost:8000/index.html* to run application.

**Comment by Ahmadbaba46** [comment]
ok, so you mean on local server. right?
what i have problem with is phonon.navigator(). but i will try on local server. thanks

**Comment by John-Henrique** [comment]
You need a web server because browser security block requests from protocol file://

**Comment by nevenne** [comment]
hi  does  anyone know web view  with picture file uploud  compatible with android, i try phonegap  and ionic and  android web view  but not work

**Comment by John-Henrique** [comment]
Can you show your code? (Please use gists or markdown tags)

**Comment by nevenne** [comment]
can you share some example, i want to uplud  picture to mysql  from android web view  or phonegap

**Comment by John-Henrique** [comment]
I don't have nothing related this, but your problem is with Phonon or Upload files? To uploads with PhoneGap you need do exactly you do in web sites, but you need some permissions (network, internet...), but save files in database isn't the better solution.

**Comment by nevenne** [comment]
yes  but nothing of that  what you say and i know not work, i try  100   examples

**Comment by Ahmadbaba46** [comment]
Ok john. It works. Thanks.

**Comment by John-Henrique** [comment]
Ok, if this question is ok, click "close" to close this issue :+1:
