### ISSUE TITLE
Help for test environment and development

### ISSUE THREAD

**Issue by LucasBurg** [quark-dev/Phonon-Framework#79]
Hello, I need some help to mount a test environment and development
for me to help in the project , thanks.

**Comment by Qathom** [comment]
Hello,

Sorry for the late reply.
The dist folder contains ready to use files and the src folder contains the "dev" files.
Also, Phonon uses Stylus. If you want to edit the default style, you can edit the file **src/stylus/_variables.styl** then run ```gulp css-all```

PS: when you fork Phonon, do not forget to run ```npm install```.
