### ISSUE TITLE
Is there a way to only use UI components of Phonon?

### ISSUE THREAD

**Issue by prijindal** [quark-dev/Phonon-Framework#8]
I want to use phonon in an angularJs project.
Though i know there is an example where you are using phonon with angular
But i wanted to use only the UI components of Phonon and let Angular handle all the routing.
Is there a way to do so?

**Comment by Qathom** [comment]
This is a good point. I added an option (useHash) to use or not hash routing. The default value is true.
```javascript
phonon.options({
         navigator: {
                defaultPage: 'home',
                animatePages: true,
                enableBrowserBackButton: true,
                templateRootDirectory: './',
                useHash: false /* false to disable hash routing, true otherwise */
         }
  });
```
