### ISSUE TITLE
More global page events

### ISSUE THREAD

**Issue by zhengnz** [quark-dev/Phonon-Framework#80]
Hello, I found phonon had 'pagecreated' and 'pageopened', but it hard to use for mvvm.
Could you support more events like framework7?

**Comment by John-Henrique** [comment]
Framework7 looks like jQuery Mobile, really have more page events. Phonon have only this events from [Core Navigator](http://phonon.quarkdev.com/docs/navigator)

**Comment by LucasBurg** [comment]
I believe that fewer events leave more organized code. My humble opnion.

**Comment by John-Henrique** [comment]
Yes, by now we have only this events, but you can fork project and add new events or changes :+1:

**Comment by Qathom** [comment]
@zhengnz : you mean more events like pageclosing, pageclosed, on page animation.. etc?

**Comment by zhengnz** [comment]
@Qathom Yes, beacause I can use these event bind model or unbind model.

**Comment by Qathom** [comment]
@zhengnz I added more global events! Please see: [the documentation under the "global events section"](http://phonon.quarkdev.com/docs/navigator)
