### ISSUE TITLE
Component popovers - Header over popover

### ISSUE THREAD

**Issue by John-Henrique** [quark-dev/Phonon-Framework#81]
Android 4.1.2
Simple HTML (same of pizza app)
Screen MDPI (480x320 px or 320x480px)
![screenshot_2016-01-15-17-46-07](https://cloud.githubusercontent.com/assets/332925/12363581/ad1907de-bbb0-11e5-9492-ccb482e95806.png)
![screenshot_2016-01-15-17-46-13](https://cloud.githubusercontent.com/assets/332925/12363582/ad3e611e-bbb0-11e5-8ca4-1e93f236da60.png)

**Comment by Qathom** [comment]
Did you try to put the popover outside of the page scope?

**Comment by John-Henrique** [comment]
Sorry, I put popover inside page scope :unamused: 

Thank you...

**Comment by Qathom** [comment]
Android 4.1 is not "logical" when the popover is inside a page scope, but since Android 4.4 it does not matter if it is inside or outside the page scope :)

**Comment by John-Henrique** [comment]
Nice tip, thanks...
