### ISSUE TITLE
Differences between phonon.min.css and phonon.css

### ISSUE THREAD

**Issue by John-Henrique** [quark-dev/Phonon-Framework#82]
I still testing and found this mistake. Look this differences in header with h1.

this is the HTML
````html
<header class="header-bar">
		<h1 class="title">My Title</title>
</header>
````
phonon.css
![phonon](https://cloud.githubusercontent.com/assets/332925/12401081/3d868d58-be0b-11e5-9831-400af76f88af.jpg)

phonon.min.css
![phonon-min](https://cloud.githubusercontent.com/assets/332925/12401089/5273a228-be0b-11e5-92f8-e73db3c21184.jpg)

**Comment by LucasBurg** [comment]
+

**Comment by Qathom** [comment]
Very strange..
I changed the gulp package for CSS "minification".
Does it change something with the latest release (1.1.8) ?

Thank you in advance!

**Comment by John-Henrique** [comment]
@Qathom yes I'm using 1.1.8, I'll try with this new release [1.1.9](https://github.com/quark-dev/Phonon-Framework/releases/tag/v1.1.9) and return back.

**Comment by John-Henrique** [comment]
I tested with release [1.1.9](https://github.com/quark-dev/Phonon-Framework/releases/tag/v1.1.9) this is fixed.

:+1:
