### ISSUE TITLE
Page + Navigation problem

### ISSUE THREAD

**Issue by snsxn** [quark-dev/Phonon-Framework#84]
I'm having problems with page navigation:
```
<button data-navigation="page-name">Go to page</button>
```
Not working.
```
<button data-navigation="$previous-page">Back</button>
```
Not working.
```
<a href="#!page-name">Go to page</a>
```
Working fine.

Am I missing something?

**Comment by John-Henrique** [comment]
Your HTML looks like correct to me... but I don`t remember if is necessary add the btn class param to create action to button.

$previous-page works only after visit a page.

Try and return here...

**Comment by John-Henrique** [comment]
I thinking, if happaning a JavaScript error buttons not working, because the actions from him are put with JavaScript.

**Comment by Qathom** [comment]
@John-Henrique :+1: 
```$previous-page``` does not work in the default page.

Please, reopen the issue if you used this in another page.
