### ISSUE TITLE
Links within a list working just once

### ISSUE THREAD

**Issue by Emethium** [quark-dev/Phonon-Framework#86]
I've been trying to create a list with links in my home screen, so a full panel containing info is opened every time the link is touched. My problem is, after I close the full panel that is successfully opened, all the links within the list stop working.

The list is written as follows:
```
<ul class="list" id="myList">
       <li><a href="#item" class="padded-list" data-panel-id="item1">Link 1</a></li>
       <li><a href="#item" class="padded-list" data-panel-id="item2">Link 2</a></li>
       <li><a href="#item" class="padded-list" data-panel-id="item3">Link 3</a></li>
</ul>  
```
The full panel was written this way:
```
<div id="item" class="panel-full">
        <header class="header-bar">
            <a class="btn icon icon-close pull-right" href="#" data-panel-close="true"></a>
            <h1 class="title center"> Info 1</h1>
        </header>

        <div class="content">
            <h3>  Information</h3>
            <p class="padded-full"> Description here</p>
        </div>
    </div>
```
So, after a link is opened once and I return to the main screen, touching any of the items does not open the referenced full panel. What is the issue?

**Comment by John-Henrique** [comment]
At this momment I don't know what causes this problem, but was reported in #71. We're waiting for @Qathom to give us a help.

**Comment by Qathom** [comment]
Hi @Emethium,

Does the latest release fix your issue?
Thanks in advance.

**Comment by Emethium** [comment]
@Qathom Yes! The issue is completely fixed :)

Thank you for the fix and the support.
