### ISSUE TITLE
backbutton to exit app(cordova), how to do this?

### ISSUE THREAD

**Issue by txchen** [quark-dev/Phonon-Framework#88]
phonon.js handles backbutton event in cordova, this prevents the default cordova behavior: press back button in the home page to exit the app.

How should we bring back this? Thanks a lot!

**Comment by John-Henrique** [comment]
You can use something like this https://gist.github.com/John-Henrique/b7ecd97147604438356d

**Comment by txchen** [comment]
Thanks! So how can I know the current page is the entry? For normal navigation after the entry, I think the back button should go back, when there is no previous page, it should exit.

**Comment by John-Henrique** [comment]
Please read Docs, it's interesting [Phonon Navigator](http://phonon.quarkdev.com/docs/navigator)

**Comment by Qathom** [comment]
@txchen : I changed the behavior of the backbutton.
I will add this patch in the **release 1.2.0** (coming asap).
(https://github.com/quark-dev/Phonon-Framework/releases)[https://github.com/quark-dev/Phonon-Framework/releases]
