### ISSUE TITLE
Icon not Displaying on Android Jelly Beam

### ISSUE THREAD

**Issue by martinschilliger** [quark-dev/Phonon-Framework#89]
The Icons that are used in Phonon do not display on Android Jelly Beam, at least for me in the header-bar-button:
```
<header class="header-bar">
	<button class="btn icon icon-menu pull-left show-for-phone-only" data-side-panel-id="side-panel"></button>
	<div class="center">
		<h1 class="title page-title">I'm the homepage-title</h1>
	</div>
</header>
```
I found out, that adding `text-rendering: auto;` to the icon-class fixed this problem, according to https://github.com/FortAwesome/Font-Awesome/issues/862#issuecomment-17429585 I added
```
button.icon {
	text-rendering: auto;
}
```
to my CSS-File.

Maybe I can help someone with this information.

**Comment by Qathom** [comment]
I just added this, thank you!
