### ISSUE TITLE
Change page after dialog confirm

### ISSUE THREAD

**Issue by hunbubu** [quark-dev/Phonon-Framework#9]
I would like change page after the user confirms a dialog box. The navigator is changing but page is not after the dialog. My example code:

```javascript

confirm.on('confirm', function(){
   app.changePage('home');
});

```

**Comment by Qathom** [comment]
The navigator module checks if a dialog is visible. If it is the case, it will cancel the page and close the active dialog instead (native-like purpose). Try to put a timeout before changing the page like so:
```javascript
window.setTimeout(function() {
    app.changePage('home');
}, 500); /* 500ms should be enough (time to dismiss the dialog) */
```
It should fix your problem. Please let me know.

**Comment by hunbubu** [comment]
Thanks, your solution works well.

**Comment by Qathom** [comment]
You no longer need to use a timeout since v1.0.3 :)

**Comment by HugoCrd** [comment]
:+1: Thanks

**Comment by hunbubu** [comment]
Thanks. It works well, only one feedback for future:

On older Android devices, the timeout you set isn't enough. The animations can't be finished and app "freezes". I think the page changes happens before animation overlay could fully disappear.
