### ISSUE TITLE
theme.css has a little error

### ISSUE THREAD

**Issue by John-Henrique** [quark-dev/Phonon-Framework#91]
I found this problem at [line 84](https://github.com/quark-dev/Phonon-Framework/blob/master/dist/css/theme.css#L84)
![phonon-alert](https://cloud.githubusercontent.com/assets/332925/12999852/c4d4fe4c-d13a-11e5-81d9-3ffeca3274d6.jpg)

This overwrite button of alert. I just comment him.

**Comment by John-Henrique** [comment]
Not fixed in Phonon 1.2.1

**Comment by Qathom** [comment]
Thank you.
Fixed in the release 1.2.2 (coming asap) :)
