### ISSUE TITLE
what's the recommended way to include Phonon.js in a project?

### ISSUE THREAD

**Issue by cloudship** [quark-dev/Phonon-Framework#95]
Hi, I raise this question because I didn't find Phonon framework in NPM, which means it cannot be included via package.json and npm install.

Is there a recommended way to include Phonon into a project and manage the upgrade easily? Thanks

**Comment by Qathom** [comment]
HI @cloudship,

For the moment, you have to include files that you need from the **dist** folder.
A npm package will come soon :)

**Comment by cloudship** [comment]
good to hear that !

**Comment by goomatyi** [comment]
Need to use any documentation

**Comment by Qathom** [comment]
You can now read the [quick start](https://github.com/quark-dev/Phonon-Framework#quick-start)!
