### ISSUE TITLE
Putting HTML elements to an accordion list head label broke the show/hide function

### ISSUE THREAD

**Issue by fqboy** [quark-dev/Phonon-Framework#96]
Hi,

If i put an HTML element in the link to open the accordion content, the show/hide functionnality is broken.

Exemple : 
`<ul class="list"><li>
						<i class="pull-right icon icon-expand-more"></i>
						<a href="#link1" class="padded-list">
							<span>Text in span</span> Text outside span
</a></li>
</ul>`

If i tap on the span element, nothing happens.

I think the listener is only on the link element.

**Comment by John-Henrique** [comment]
Your HTML is broken, see the tag A

**Comment by fqboy** [comment]
Sorry forgot it in the example. Still a bug.

**Comment by Qathom** [comment]
Hello @fqboy,

Thank you for reporting this.
It will be fixed in the release 1.2.2 (coming asap).

**Comment by Qathom** [comment]
Please, reopen the issue if it does not work for you.

**Comment by fqboy** [comment]
Thank you, seems working !
