### ISSUE TITLE
If an accordion list is open, the content is still displayed in the side panel

### ISSUE THREAD

**Issue by fqboy** [quark-dev/Phonon-Framework#97]
Hi,

When i open an accordion list, and then i go back to a side panel, the accordion content is stil displayed.

Demo : http://imgur.com/U6YxXrD

**Comment by John-Henrique** [comment]
This elements have a same id or class?

**Comment by fqboy** [comment]
No, the example linked comes from the kitchen sink

**Comment by EmanuelM** [comment]
I have the same error and I need to fix it as fast as possible!

**Comment by Qathom** [comment]
Hello,

Thank you for reporting this.
I am working on it.

**Comment by Qathom** [comment]
Fixed in the latest release **1.2.2**!
When the users closes the page contaning an accordion list, Phonon will close it automatically.

Please, tell me if it works for your :)

**Comment by EmanuelM** [comment]
Yes, it works!!!

Really thanks ♥

**Comment by fqboy** [comment]
Thank you !
